// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type InsertionPointsInitParameters struct {

	// (String) Content that goes inside the form
	// Content that goes inside the form
	FormContent *string `json:"formContent,omitempty" tf:"form_content,omitempty"`

	// (String) Content that goes at the end of the form.
	// Content that goes at the end of the form.
	FormContentEnd *string `json:"formContentEnd,omitempty" tf:"form_content_end,omitempty"`

	// (String) Content that goes at the start of the form.
	// Content that goes at the start of the form.
	FormContentStart *string `json:"formContentStart,omitempty" tf:"form_content_start,omitempty"`

	// (String) Footer content for the end of the footer.
	// Footer content for the end of the footer.
	FormFooterEnd *string `json:"formFooterEnd,omitempty" tf:"form_footer_end,omitempty"`

	// (String) Footer content for the start of the footer.
	// Footer content for the start of the footer.
	FormFooterStart *string `json:"formFooterStart,omitempty" tf:"form_footer_start,omitempty"`

	// (String) Actions that go at the end of secondary actions.
	// Actions that go at the end of secondary actions.
	SecondaryActionsEnd *string `json:"secondaryActionsEnd,omitempty" tf:"secondary_actions_end,omitempty"`

	// (String) Actions that go at the start of secondary actions.
	// Actions that go at the start of secondary actions.
	SecondaryActionsStart *string `json:"secondaryActionsStart,omitempty" tf:"secondary_actions_start,omitempty"`
}

type InsertionPointsObservation struct {

	// (String) Content that goes inside the form
	// Content that goes inside the form
	FormContent *string `json:"formContent,omitempty" tf:"form_content,omitempty"`

	// (String) Content that goes at the end of the form.
	// Content that goes at the end of the form.
	FormContentEnd *string `json:"formContentEnd,omitempty" tf:"form_content_end,omitempty"`

	// (String) Content that goes at the start of the form.
	// Content that goes at the start of the form.
	FormContentStart *string `json:"formContentStart,omitempty" tf:"form_content_start,omitempty"`

	// (String) Footer content for the end of the footer.
	// Footer content for the end of the footer.
	FormFooterEnd *string `json:"formFooterEnd,omitempty" tf:"form_footer_end,omitempty"`

	// (String) Footer content for the start of the footer.
	// Footer content for the start of the footer.
	FormFooterStart *string `json:"formFooterStart,omitempty" tf:"form_footer_start,omitempty"`

	// (String) Actions that go at the end of secondary actions.
	// Actions that go at the end of secondary actions.
	SecondaryActionsEnd *string `json:"secondaryActionsEnd,omitempty" tf:"secondary_actions_end,omitempty"`

	// (String) Actions that go at the start of secondary actions.
	// Actions that go at the start of secondary actions.
	SecondaryActionsStart *string `json:"secondaryActionsStart,omitempty" tf:"secondary_actions_start,omitempty"`
}

type InsertionPointsParameters struct {

	// (String) Content that goes inside the form
	// Content that goes inside the form
	// +kubebuilder:validation:Optional
	FormContent *string `json:"formContent,omitempty" tf:"form_content,omitempty"`

	// (String) Content that goes at the end of the form.
	// Content that goes at the end of the form.
	// +kubebuilder:validation:Optional
	FormContentEnd *string `json:"formContentEnd,omitempty" tf:"form_content_end,omitempty"`

	// (String) Content that goes at the start of the form.
	// Content that goes at the start of the form.
	// +kubebuilder:validation:Optional
	FormContentStart *string `json:"formContentStart,omitempty" tf:"form_content_start,omitempty"`

	// (String) Footer content for the end of the footer.
	// Footer content for the end of the footer.
	// +kubebuilder:validation:Optional
	FormFooterEnd *string `json:"formFooterEnd,omitempty" tf:"form_footer_end,omitempty"`

	// (String) Footer content for the start of the footer.
	// Footer content for the start of the footer.
	// +kubebuilder:validation:Optional
	FormFooterStart *string `json:"formFooterStart,omitempty" tf:"form_footer_start,omitempty"`

	// (String) Actions that go at the end of secondary actions.
	// Actions that go at the end of secondary actions.
	// +kubebuilder:validation:Optional
	SecondaryActionsEnd *string `json:"secondaryActionsEnd,omitempty" tf:"secondary_actions_end,omitempty"`

	// (String) Actions that go at the start of secondary actions.
	// Actions that go at the start of secondary actions.
	// +kubebuilder:validation:Optional
	SecondaryActionsStart *string `json:"secondaryActionsStart,omitempty" tf:"secondary_actions_start,omitempty"`
}

type ScreenPartialsInitParameters struct {

	// id, login, login-password, signup, signup-id, signup-password, login-passwordless, customized-consent.
	// The prompt that you are adding partials for. Options are: `login-id`, `login`, `login-password`, `signup`, `signup-id`, `signup-password`, `login-passwordless`, `customized-consent`.
	PromptType *string `json:"promptType,omitempty" tf:"prompt_type,omitempty"`

	// (Block List) (see below for nested schema)
	ScreenPartials []ScreenPartialsScreenPartialsInitParameters `json:"screenPartials,omitempty" tf:"screen_partials,omitempty"`
}

type ScreenPartialsObservation struct {

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// id, login, login-password, signup, signup-id, signup-password, login-passwordless, customized-consent.
	// The prompt that you are adding partials for. Options are: `login-id`, `login`, `login-password`, `signup`, `signup-id`, `signup-password`, `login-passwordless`, `customized-consent`.
	PromptType *string `json:"promptType,omitempty" tf:"prompt_type,omitempty"`

	// (Block List) (see below for nested schema)
	ScreenPartials []ScreenPartialsScreenPartialsObservation `json:"screenPartials,omitempty" tf:"screen_partials,omitempty"`
}

type ScreenPartialsParameters struct {

	// id, login, login-password, signup, signup-id, signup-password, login-passwordless, customized-consent.
	// The prompt that you are adding partials for. Options are: `login-id`, `login`, `login-password`, `signup`, `signup-id`, `signup-password`, `login-passwordless`, `customized-consent`.
	// +kubebuilder:validation:Optional
	PromptType *string `json:"promptType,omitempty" tf:"prompt_type,omitempty"`

	// (Block List) (see below for nested schema)
	// +kubebuilder:validation:Optional
	ScreenPartials []ScreenPartialsScreenPartialsParameters `json:"screenPartials,omitempty" tf:"screen_partials,omitempty"`
}

type ScreenPartialsScreenPartialsInitParameters struct {

	// (Block List, Min: 1, Max: 1) (see below for nested schema)
	InsertionPoints []InsertionPointsInitParameters `json:"insertionPoints,omitempty" tf:"insertion_points,omitempty"`

	// (String) The name of the screen associated with the partials
	// The name of the screen associated with the partials
	ScreenName *string `json:"screenName,omitempty" tf:"screen_name,omitempty"`
}

type ScreenPartialsScreenPartialsObservation struct {

	// (Block List, Min: 1, Max: 1) (see below for nested schema)
	InsertionPoints []InsertionPointsObservation `json:"insertionPoints,omitempty" tf:"insertion_points,omitempty"`

	// (String) The name of the screen associated with the partials
	// The name of the screen associated with the partials
	ScreenName *string `json:"screenName,omitempty" tf:"screen_name,omitempty"`
}

type ScreenPartialsScreenPartialsParameters struct {

	// (Block List, Min: 1, Max: 1) (see below for nested schema)
	// +kubebuilder:validation:Optional
	InsertionPoints []InsertionPointsParameters `json:"insertionPoints" tf:"insertion_points,omitempty"`

	// (String) The name of the screen associated with the partials
	// The name of the screen associated with the partials
	// +kubebuilder:validation:Optional
	ScreenName *string `json:"screenName" tf:"screen_name,omitempty"`
}

// ScreenPartialsSpec defines the desired state of ScreenPartials
type ScreenPartialsSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ScreenPartialsParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ScreenPartialsInitParameters `json:"initProvider,omitempty"`
}

// ScreenPartialsStatus defines the observed state of ScreenPartials.
type ScreenPartialsStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ScreenPartialsObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ScreenPartials is the Schema for the ScreenPartialss API. With this resource, you can manage a customized sign up and login experience by adding custom content, form elements and css/javascript. You can read more about this here https://auth0.com/docs/customize/universal-login-pages/customize-signup-and-login-prompts.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,auth0}
type ScreenPartials struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.promptType) || (has(self.initProvider) && has(self.initProvider.promptType))",message="spec.forProvider.promptType is a required parameter"
	Spec   ScreenPartialsSpec   `json:"spec"`
	Status ScreenPartialsStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ScreenPartialsList contains a list of ScreenPartialss
type ScreenPartialsList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ScreenPartials `json:"items"`
}

// Repository type metadata.
var (
	ScreenPartials_Kind             = "ScreenPartials"
	ScreenPartials_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ScreenPartials_Kind}.String()
	ScreenPartials_KindAPIVersion   = ScreenPartials_Kind + "." + CRDGroupVersion.String()
	ScreenPartials_GroupVersionKind = CRDGroupVersion.WithKind(ScreenPartials_Kind)
)

func init() {
	SchemeBuilder.Register(&ScreenPartials{}, &ScreenPartialsList{})
}
