// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type PermissionInitParameters struct {

	// (String) Name of the permission.
	// Name of the permission.
	Permission *string `json:"permission,omitempty" tf:"permission,omitempty"`

	// (String) Identifier of the resource server that the permission is associated with.
	// Identifier of the resource server that the permission is associated with.
	ResourceServerIdentifier *string `json:"resourceServerIdentifier,omitempty" tf:"resource_server_identifier,omitempty"`

	// (String) ID of the role to associate the permission to.
	// ID of the role to associate the permission to.
	RoleID *string `json:"roleId,omitempty" tf:"role_id,omitempty"`
}

type PermissionObservation struct {

	// (String) Description of the permission.
	// Description of the permission.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Name of the permission.
	// Name of the permission.
	Permission *string `json:"permission,omitempty" tf:"permission,omitempty"`

	// (String) Identifier of the resource server that the permission is associated with.
	// Identifier of the resource server that the permission is associated with.
	ResourceServerIdentifier *string `json:"resourceServerIdentifier,omitempty" tf:"resource_server_identifier,omitempty"`

	// (String) Name of the resource server that the permission is associated with.
	// Name of the resource server that the permission is associated with.
	ResourceServerName *string `json:"resourceServerName,omitempty" tf:"resource_server_name,omitempty"`

	// (String) ID of the role to associate the permission to.
	// ID of the role to associate the permission to.
	RoleID *string `json:"roleId,omitempty" tf:"role_id,omitempty"`
}

type PermissionParameters struct {

	// (String) Name of the permission.
	// Name of the permission.
	// +kubebuilder:validation:Optional
	Permission *string `json:"permission,omitempty" tf:"permission,omitempty"`

	// (String) Identifier of the resource server that the permission is associated with.
	// Identifier of the resource server that the permission is associated with.
	// +kubebuilder:validation:Optional
	ResourceServerIdentifier *string `json:"resourceServerIdentifier,omitempty" tf:"resource_server_identifier,omitempty"`

	// (String) ID of the role to associate the permission to.
	// ID of the role to associate the permission to.
	// +kubebuilder:validation:Optional
	RoleID *string `json:"roleId,omitempty" tf:"role_id,omitempty"`
}

// PermissionSpec defines the desired state of Permission
type PermissionSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     PermissionParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider PermissionInitParameters `json:"initProvider,omitempty"`
}

// PermissionStatus defines the observed state of Permission.
type PermissionStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        PermissionObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Permission is the Schema for the Permissions API. With this resource, you can manage role permissions (1-1).
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,auth0}
type Permission struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.permission) || (has(self.initProvider) && has(self.initProvider.permission))",message="spec.forProvider.permission is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.resourceServerIdentifier) || (has(self.initProvider) && has(self.initProvider.resourceServerIdentifier))",message="spec.forProvider.resourceServerIdentifier is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.roleId) || (has(self.initProvider) && has(self.initProvider.roleId))",message="spec.forProvider.roleId is a required parameter"
	Spec   PermissionSpec   `json:"spec"`
	Status PermissionStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// PermissionList contains a list of Permissions
type PermissionList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Permission `json:"items"`
}

// Repository type metadata.
var (
	Permission_Kind             = "Permission"
	Permission_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Permission_Kind}.String()
	Permission_KindAPIVersion   = Permission_Kind + "." + CRDGroupVersion.String()
	Permission_GroupVersionKind = CRDGroupVersion.WithKind(Permission_Kind)
)

func init() {
	SchemeBuilder.Register(&Permission{}, &PermissionList{})
}
