//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScreenRenderer) DeepCopyInto(out *ScreenRenderer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScreenRenderer.
func (in *ScreenRenderer) DeepCopy() *ScreenRenderer {
	if in == nil {
		return nil
	}
	out := new(ScreenRenderer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ScreenRenderer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScreenRendererInitParameters) DeepCopyInto(out *ScreenRendererInitParameters) {
	*out = *in
	if in.ContextConfiguration != nil {
		in, out := &in.ContextConfiguration, &out.ContextConfiguration
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.DefaultHeadTagsDisabled != nil {
		in, out := &in.DefaultHeadTagsDisabled, &out.DefaultHeadTagsDisabled
		*out = new(bool)
		**out = **in
	}
	if in.HeadTags != nil {
		in, out := &in.HeadTags, &out.HeadTags
		*out = new(string)
		**out = **in
	}
	if in.PromptType != nil {
		in, out := &in.PromptType, &out.PromptType
		*out = new(string)
		**out = **in
	}
	if in.RenderingMode != nil {
		in, out := &in.RenderingMode, &out.RenderingMode
		*out = new(string)
		**out = **in
	}
	if in.ScreenName != nil {
		in, out := &in.ScreenName, &out.ScreenName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScreenRendererInitParameters.
func (in *ScreenRendererInitParameters) DeepCopy() *ScreenRendererInitParameters {
	if in == nil {
		return nil
	}
	out := new(ScreenRendererInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScreenRendererList) DeepCopyInto(out *ScreenRendererList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ScreenRenderer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScreenRendererList.
func (in *ScreenRendererList) DeepCopy() *ScreenRendererList {
	if in == nil {
		return nil
	}
	out := new(ScreenRendererList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ScreenRendererList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScreenRendererObservation) DeepCopyInto(out *ScreenRendererObservation) {
	*out = *in
	if in.ContextConfiguration != nil {
		in, out := &in.ContextConfiguration, &out.ContextConfiguration
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.DefaultHeadTagsDisabled != nil {
		in, out := &in.DefaultHeadTagsDisabled, &out.DefaultHeadTagsDisabled
		*out = new(bool)
		**out = **in
	}
	if in.HeadTags != nil {
		in, out := &in.HeadTags, &out.HeadTags
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.PromptType != nil {
		in, out := &in.PromptType, &out.PromptType
		*out = new(string)
		**out = **in
	}
	if in.RenderingMode != nil {
		in, out := &in.RenderingMode, &out.RenderingMode
		*out = new(string)
		**out = **in
	}
	if in.ScreenName != nil {
		in, out := &in.ScreenName, &out.ScreenName
		*out = new(string)
		**out = **in
	}
	if in.Tenant != nil {
		in, out := &in.Tenant, &out.Tenant
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScreenRendererObservation.
func (in *ScreenRendererObservation) DeepCopy() *ScreenRendererObservation {
	if in == nil {
		return nil
	}
	out := new(ScreenRendererObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScreenRendererParameters) DeepCopyInto(out *ScreenRendererParameters) {
	*out = *in
	if in.ContextConfiguration != nil {
		in, out := &in.ContextConfiguration, &out.ContextConfiguration
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.DefaultHeadTagsDisabled != nil {
		in, out := &in.DefaultHeadTagsDisabled, &out.DefaultHeadTagsDisabled
		*out = new(bool)
		**out = **in
	}
	if in.HeadTags != nil {
		in, out := &in.HeadTags, &out.HeadTags
		*out = new(string)
		**out = **in
	}
	if in.PromptType != nil {
		in, out := &in.PromptType, &out.PromptType
		*out = new(string)
		**out = **in
	}
	if in.RenderingMode != nil {
		in, out := &in.RenderingMode, &out.RenderingMode
		*out = new(string)
		**out = **in
	}
	if in.ScreenName != nil {
		in, out := &in.ScreenName, &out.ScreenName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScreenRendererParameters.
func (in *ScreenRendererParameters) DeepCopy() *ScreenRendererParameters {
	if in == nil {
		return nil
	}
	out := new(ScreenRendererParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScreenRendererSpec) DeepCopyInto(out *ScreenRendererSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScreenRendererSpec.
func (in *ScreenRendererSpec) DeepCopy() *ScreenRendererSpec {
	if in == nil {
		return nil
	}
	out := new(ScreenRendererSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScreenRendererStatus) DeepCopyInto(out *ScreenRendererStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScreenRendererStatus.
func (in *ScreenRendererStatus) DeepCopy() *ScreenRendererStatus {
	if in == nil {
		return nil
	}
	out := new(ScreenRendererStatus)
	in.DeepCopyInto(out)
	return out
}
