//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomerProvidedRootKeyInitParameters) DeepCopyInto(out *CustomerProvidedRootKeyInitParameters) {
	*out = *in
	if in.WrappedKey != nil {
		in, out := &in.WrappedKey, &out.WrappedKey
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomerProvidedRootKeyInitParameters.
func (in *CustomerProvidedRootKeyInitParameters) DeepCopy() *CustomerProvidedRootKeyInitParameters {
	if in == nil {
		return nil
	}
	out := new(CustomerProvidedRootKeyInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomerProvidedRootKeyObservation) DeepCopyInto(out *CustomerProvidedRootKeyObservation) {
	*out = *in
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = new(string)
		**out = **in
	}
	if in.KeyID != nil {
		in, out := &in.KeyID, &out.KeyID
		*out = new(string)
		**out = **in
	}
	if in.ParentKeyID != nil {
		in, out := &in.ParentKeyID, &out.ParentKeyID
		*out = new(string)
		**out = **in
	}
	if in.PublicWrappingKey != nil {
		in, out := &in.PublicWrappingKey, &out.PublicWrappingKey
		*out = new(string)
		**out = **in
	}
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = new(string)
		**out = **in
	}
	if in.WrappedKey != nil {
		in, out := &in.WrappedKey, &out.WrappedKey
		*out = new(string)
		**out = **in
	}
	if in.WrappingAlgorithm != nil {
		in, out := &in.WrappingAlgorithm, &out.WrappingAlgorithm
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomerProvidedRootKeyObservation.
func (in *CustomerProvidedRootKeyObservation) DeepCopy() *CustomerProvidedRootKeyObservation {
	if in == nil {
		return nil
	}
	out := new(CustomerProvidedRootKeyObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomerProvidedRootKeyParameters) DeepCopyInto(out *CustomerProvidedRootKeyParameters) {
	*out = *in
	if in.WrappedKey != nil {
		in, out := &in.WrappedKey, &out.WrappedKey
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomerProvidedRootKeyParameters.
func (in *CustomerProvidedRootKeyParameters) DeepCopy() *CustomerProvidedRootKeyParameters {
	if in == nil {
		return nil
	}
	out := new(CustomerProvidedRootKeyParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EncryptionKeysInitParameters) DeepCopyInto(out *EncryptionKeysInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EncryptionKeysInitParameters.
func (in *EncryptionKeysInitParameters) DeepCopy() *EncryptionKeysInitParameters {
	if in == nil {
		return nil
	}
	out := new(EncryptionKeysInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EncryptionKeysObservation) DeepCopyInto(out *EncryptionKeysObservation) {
	*out = *in
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = new(string)
		**out = **in
	}
	if in.KeyID != nil {
		in, out := &in.KeyID, &out.KeyID
		*out = new(string)
		**out = **in
	}
	if in.ParentKeyID != nil {
		in, out := &in.ParentKeyID, &out.ParentKeyID
		*out = new(string)
		**out = **in
	}
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EncryptionKeysObservation.
func (in *EncryptionKeysObservation) DeepCopy() *EncryptionKeysObservation {
	if in == nil {
		return nil
	}
	out := new(EncryptionKeysObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EncryptionKeysParameters) DeepCopyInto(out *EncryptionKeysParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EncryptionKeysParameters.
func (in *EncryptionKeysParameters) DeepCopy() *EncryptionKeysParameters {
	if in == nil {
		return nil
	}
	out := new(EncryptionKeysParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeyManager) DeepCopyInto(out *KeyManager) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyManager.
func (in *KeyManager) DeepCopy() *KeyManager {
	if in == nil {
		return nil
	}
	out := new(KeyManager)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeyManager) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeyManagerInitParameters) DeepCopyInto(out *KeyManagerInitParameters) {
	*out = *in
	if in.CustomerProvidedRootKey != nil {
		in, out := &in.CustomerProvidedRootKey, &out.CustomerProvidedRootKey
		*out = make([]CustomerProvidedRootKeyInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.KeyRotationID != nil {
		in, out := &in.KeyRotationID, &out.KeyRotationID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyManagerInitParameters.
func (in *KeyManagerInitParameters) DeepCopy() *KeyManagerInitParameters {
	if in == nil {
		return nil
	}
	out := new(KeyManagerInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeyManagerList) DeepCopyInto(out *KeyManagerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KeyManager, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyManagerList.
func (in *KeyManagerList) DeepCopy() *KeyManagerList {
	if in == nil {
		return nil
	}
	out := new(KeyManagerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeyManagerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeyManagerObservation) DeepCopyInto(out *KeyManagerObservation) {
	*out = *in
	if in.CustomerProvidedRootKey != nil {
		in, out := &in.CustomerProvidedRootKey, &out.CustomerProvidedRootKey
		*out = make([]CustomerProvidedRootKeyObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.EncryptionKeys != nil {
		in, out := &in.EncryptionKeys, &out.EncryptionKeys
		*out = make([]EncryptionKeysObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.KeyRotationID != nil {
		in, out := &in.KeyRotationID, &out.KeyRotationID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyManagerObservation.
func (in *KeyManagerObservation) DeepCopy() *KeyManagerObservation {
	if in == nil {
		return nil
	}
	out := new(KeyManagerObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeyManagerParameters) DeepCopyInto(out *KeyManagerParameters) {
	*out = *in
	if in.CustomerProvidedRootKey != nil {
		in, out := &in.CustomerProvidedRootKey, &out.CustomerProvidedRootKey
		*out = make([]CustomerProvidedRootKeyParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.KeyRotationID != nil {
		in, out := &in.KeyRotationID, &out.KeyRotationID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyManagerParameters.
func (in *KeyManagerParameters) DeepCopy() *KeyManagerParameters {
	if in == nil {
		return nil
	}
	out := new(KeyManagerParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeyManagerSpec) DeepCopyInto(out *KeyManagerSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyManagerSpec.
func (in *KeyManagerSpec) DeepCopy() *KeyManagerSpec {
	if in == nil {
		return nil
	}
	out := new(KeyManagerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeyManagerStatus) DeepCopyInto(out *KeyManagerStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyManagerStatus.
func (in *KeyManagerStatus) DeepCopy() *KeyManagerStatus {
	if in == nil {
		return nil
	}
	out := new(KeyManagerStatus)
	in.DeepCopyInto(out)
	return out
}
