//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BrandingInitParameters) DeepCopyInto(out *BrandingInitParameters) {
	*out = *in
	if in.Colors != nil {
		in, out := &in.Colors, &out.Colors
		*out = make([]ColorsInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LogoURL != nil {
		in, out := &in.LogoURL, &out.LogoURL
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BrandingInitParameters.
func (in *BrandingInitParameters) DeepCopy() *BrandingInitParameters {
	if in == nil {
		return nil
	}
	out := new(BrandingInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BrandingObservation) DeepCopyInto(out *BrandingObservation) {
	*out = *in
	if in.Colors != nil {
		in, out := &in.Colors, &out.Colors
		*out = make([]ColorsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LogoURL != nil {
		in, out := &in.LogoURL, &out.LogoURL
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BrandingObservation.
func (in *BrandingObservation) DeepCopy() *BrandingObservation {
	if in == nil {
		return nil
	}
	out := new(BrandingObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BrandingParameters) DeepCopyInto(out *BrandingParameters) {
	*out = *in
	if in.Colors != nil {
		in, out := &in.Colors, &out.Colors
		*out = make([]ColorsParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LogoURL != nil {
		in, out := &in.LogoURL, &out.LogoURL
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BrandingParameters.
func (in *BrandingParameters) DeepCopy() *BrandingParameters {
	if in == nil {
		return nil
	}
	out := new(BrandingParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ColorsInitParameters) DeepCopyInto(out *ColorsInitParameters) {
	*out = *in
	if in.Primary != nil {
		in, out := &in.Primary, &out.Primary
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ColorsInitParameters.
func (in *ColorsInitParameters) DeepCopy() *ColorsInitParameters {
	if in == nil {
		return nil
	}
	out := new(ColorsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ColorsObservation) DeepCopyInto(out *ColorsObservation) {
	*out = *in
	if in.Primary != nil {
		in, out := &in.Primary, &out.Primary
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ColorsObservation.
func (in *ColorsObservation) DeepCopy() *ColorsObservation {
	if in == nil {
		return nil
	}
	out := new(ColorsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ColorsParameters) DeepCopyInto(out *ColorsParameters) {
	*out = *in
	if in.Primary != nil {
		in, out := &in.Primary, &out.Primary
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ColorsParameters.
func (in *ColorsParameters) DeepCopy() *ColorsParameters {
	if in == nil {
		return nil
	}
	out := new(ColorsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceProfile) DeepCopyInto(out *ServiceProfile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceProfile.
func (in *ServiceProfile) DeepCopy() *ServiceProfile {
	if in == nil {
		return nil
	}
	out := new(ServiceProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ServiceProfile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceProfileInitParameters) DeepCopyInto(out *ServiceProfileInitParameters) {
	*out = *in
	if in.AllowedStrategies != nil {
		in, out := &in.AllowedStrategies, &out.AllowedStrategies
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Branding != nil {
		in, out := &in.Branding, &out.Branding
		*out = make([]BrandingInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.UserAttributes != nil {
		in, out := &in.UserAttributes, &out.UserAttributes
		*out = make([]UserAttributesInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceProfileInitParameters.
func (in *ServiceProfileInitParameters) DeepCopy() *ServiceProfileInitParameters {
	if in == nil {
		return nil
	}
	out := new(ServiceProfileInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceProfileList) DeepCopyInto(out *ServiceProfileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ServiceProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceProfileList.
func (in *ServiceProfileList) DeepCopy() *ServiceProfileList {
	if in == nil {
		return nil
	}
	out := new(ServiceProfileList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ServiceProfileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceProfileObservation) DeepCopyInto(out *ServiceProfileObservation) {
	*out = *in
	if in.AllowedStrategies != nil {
		in, out := &in.AllowedStrategies, &out.AllowedStrategies
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Branding != nil {
		in, out := &in.Branding, &out.Branding
		*out = make([]BrandingObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = new(string)
		**out = **in
	}
	if in.UserAttributes != nil {
		in, out := &in.UserAttributes, &out.UserAttributes
		*out = make([]UserAttributesObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceProfileObservation.
func (in *ServiceProfileObservation) DeepCopy() *ServiceProfileObservation {
	if in == nil {
		return nil
	}
	out := new(ServiceProfileObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceProfileParameters) DeepCopyInto(out *ServiceProfileParameters) {
	*out = *in
	if in.AllowedStrategies != nil {
		in, out := &in.AllowedStrategies, &out.AllowedStrategies
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Branding != nil {
		in, out := &in.Branding, &out.Branding
		*out = make([]BrandingParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.UserAttributes != nil {
		in, out := &in.UserAttributes, &out.UserAttributes
		*out = make([]UserAttributesParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceProfileParameters.
func (in *ServiceProfileParameters) DeepCopy() *ServiceProfileParameters {
	if in == nil {
		return nil
	}
	out := new(ServiceProfileParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceProfileSpec) DeepCopyInto(out *ServiceProfileSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceProfileSpec.
func (in *ServiceProfileSpec) DeepCopy() *ServiceProfileSpec {
	if in == nil {
		return nil
	}
	out := new(ServiceProfileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceProfileStatus) DeepCopyInto(out *ServiceProfileStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceProfileStatus.
func (in *ServiceProfileStatus) DeepCopy() *ServiceProfileStatus {
	if in == nil {
		return nil
	}
	out := new(ServiceProfileStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserAttributesInitParameters) DeepCopyInto(out *UserAttributesInitParameters) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.IsOptional != nil {
		in, out := &in.IsOptional, &out.IsOptional
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserAttributesInitParameters.
func (in *UserAttributesInitParameters) DeepCopy() *UserAttributesInitParameters {
	if in == nil {
		return nil
	}
	out := new(UserAttributesInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserAttributesObservation) DeepCopyInto(out *UserAttributesObservation) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.IsOptional != nil {
		in, out := &in.IsOptional, &out.IsOptional
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserAttributesObservation.
func (in *UserAttributesObservation) DeepCopy() *UserAttributesObservation {
	if in == nil {
		return nil
	}
	out := new(UserAttributesObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserAttributesParameters) DeepCopyInto(out *UserAttributesParameters) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.IsOptional != nil {
		in, out := &in.IsOptional, &out.IsOptional
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserAttributesParameters.
func (in *UserAttributesParameters) DeepCopy() *UserAttributesParameters {
	if in == nil {
		return nil
	}
	out := new(UserAttributesParameters)
	in.DeepCopyInto(out)
	return out
}
