//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Branding) DeepCopyInto(out *Branding) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Branding.
func (in *Branding) DeepCopy() *Branding {
	if in == nil {
		return nil
	}
	out := new(Branding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Branding) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BrandingInitParameters) DeepCopyInto(out *BrandingInitParameters) {
	*out = *in
	if in.Colors != nil {
		in, out := &in.Colors, &out.Colors
		*out = make([]ColorsInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.FaviconURL != nil {
		in, out := &in.FaviconURL, &out.FaviconURL
		*out = new(string)
		**out = **in
	}
	if in.Font != nil {
		in, out := &in.Font, &out.Font
		*out = make([]FontInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LogoURL != nil {
		in, out := &in.LogoURL, &out.LogoURL
		*out = new(string)
		**out = **in
	}
	if in.UniversalLogin != nil {
		in, out := &in.UniversalLogin, &out.UniversalLogin
		*out = make([]UniversalLoginInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BrandingInitParameters.
func (in *BrandingInitParameters) DeepCopy() *BrandingInitParameters {
	if in == nil {
		return nil
	}
	out := new(BrandingInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BrandingList) DeepCopyInto(out *BrandingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Branding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BrandingList.
func (in *BrandingList) DeepCopy() *BrandingList {
	if in == nil {
		return nil
	}
	out := new(BrandingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BrandingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BrandingObservation) DeepCopyInto(out *BrandingObservation) {
	*out = *in
	if in.Colors != nil {
		in, out := &in.Colors, &out.Colors
		*out = make([]ColorsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.FaviconURL != nil {
		in, out := &in.FaviconURL, &out.FaviconURL
		*out = new(string)
		**out = **in
	}
	if in.Font != nil {
		in, out := &in.Font, &out.Font
		*out = make([]FontObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.LogoURL != nil {
		in, out := &in.LogoURL, &out.LogoURL
		*out = new(string)
		**out = **in
	}
	if in.UniversalLogin != nil {
		in, out := &in.UniversalLogin, &out.UniversalLogin
		*out = make([]UniversalLoginObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BrandingObservation.
func (in *BrandingObservation) DeepCopy() *BrandingObservation {
	if in == nil {
		return nil
	}
	out := new(BrandingObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BrandingParameters) DeepCopyInto(out *BrandingParameters) {
	*out = *in
	if in.Colors != nil {
		in, out := &in.Colors, &out.Colors
		*out = make([]ColorsParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.FaviconURL != nil {
		in, out := &in.FaviconURL, &out.FaviconURL
		*out = new(string)
		**out = **in
	}
	if in.Font != nil {
		in, out := &in.Font, &out.Font
		*out = make([]FontParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LogoURL != nil {
		in, out := &in.LogoURL, &out.LogoURL
		*out = new(string)
		**out = **in
	}
	if in.UniversalLogin != nil {
		in, out := &in.UniversalLogin, &out.UniversalLogin
		*out = make([]UniversalLoginParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BrandingParameters.
func (in *BrandingParameters) DeepCopy() *BrandingParameters {
	if in == nil {
		return nil
	}
	out := new(BrandingParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BrandingSpec) DeepCopyInto(out *BrandingSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BrandingSpec.
func (in *BrandingSpec) DeepCopy() *BrandingSpec {
	if in == nil {
		return nil
	}
	out := new(BrandingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BrandingStatus) DeepCopyInto(out *BrandingStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BrandingStatus.
func (in *BrandingStatus) DeepCopy() *BrandingStatus {
	if in == nil {
		return nil
	}
	out := new(BrandingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ColorsInitParameters) DeepCopyInto(out *ColorsInitParameters) {
	*out = *in
	if in.PageBackground != nil {
		in, out := &in.PageBackground, &out.PageBackground
		*out = new(string)
		**out = **in
	}
	if in.Primary != nil {
		in, out := &in.Primary, &out.Primary
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ColorsInitParameters.
func (in *ColorsInitParameters) DeepCopy() *ColorsInitParameters {
	if in == nil {
		return nil
	}
	out := new(ColorsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ColorsObservation) DeepCopyInto(out *ColorsObservation) {
	*out = *in
	if in.PageBackground != nil {
		in, out := &in.PageBackground, &out.PageBackground
		*out = new(string)
		**out = **in
	}
	if in.Primary != nil {
		in, out := &in.Primary, &out.Primary
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ColorsObservation.
func (in *ColorsObservation) DeepCopy() *ColorsObservation {
	if in == nil {
		return nil
	}
	out := new(ColorsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ColorsParameters) DeepCopyInto(out *ColorsParameters) {
	*out = *in
	if in.PageBackground != nil {
		in, out := &in.PageBackground, &out.PageBackground
		*out = new(string)
		**out = **in
	}
	if in.Primary != nil {
		in, out := &in.Primary, &out.Primary
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ColorsParameters.
func (in *ColorsParameters) DeepCopy() *ColorsParameters {
	if in == nil {
		return nil
	}
	out := new(ColorsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FontInitParameters) DeepCopyInto(out *FontInitParameters) {
	*out = *in
	if in.URL != nil {
		in, out := &in.URL, &out.URL
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FontInitParameters.
func (in *FontInitParameters) DeepCopy() *FontInitParameters {
	if in == nil {
		return nil
	}
	out := new(FontInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FontObservation) DeepCopyInto(out *FontObservation) {
	*out = *in
	if in.URL != nil {
		in, out := &in.URL, &out.URL
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FontObservation.
func (in *FontObservation) DeepCopy() *FontObservation {
	if in == nil {
		return nil
	}
	out := new(FontObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FontParameters) DeepCopyInto(out *FontParameters) {
	*out = *in
	if in.URL != nil {
		in, out := &in.URL, &out.URL
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FontParameters.
func (in *FontParameters) DeepCopy() *FontParameters {
	if in == nil {
		return nil
	}
	out := new(FontParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UniversalLoginInitParameters) DeepCopyInto(out *UniversalLoginInitParameters) {
	*out = *in
	if in.Body != nil {
		in, out := &in.Body, &out.Body
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UniversalLoginInitParameters.
func (in *UniversalLoginInitParameters) DeepCopy() *UniversalLoginInitParameters {
	if in == nil {
		return nil
	}
	out := new(UniversalLoginInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UniversalLoginObservation) DeepCopyInto(out *UniversalLoginObservation) {
	*out = *in
	if in.Body != nil {
		in, out := &in.Body, &out.Body
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UniversalLoginObservation.
func (in *UniversalLoginObservation) DeepCopy() *UniversalLoginObservation {
	if in == nil {
		return nil
	}
	out := new(UniversalLoginObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UniversalLoginParameters) DeepCopyInto(out *UniversalLoginParameters) {
	*out = *in
	if in.Body != nil {
		in, out := &in.Body, &out.Body
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UniversalLoginParameters.
func (in *UniversalLoginParameters) DeepCopy() *UniversalLoginParameters {
	if in == nil {
		return nil
	}
	out := new(UniversalLoginParameters)
	in.DeepCopyInto(out)
	return out
}
