// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type ServerScopeInitParameters struct {

	// (String) Description of the scope (permission).
	// Description of the scope (permission).
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) Identifier of the resource server that the scope (permission) is associated with.
	// Identifier of the resource server that the scope (permission) is associated with.
	ResourceServerIdentifier *string `json:"resourceServerIdentifier,omitempty" tf:"resource_server_identifier,omitempty"`

	// (String) Name of the scope (permission).
	// Name of the scope (permission).
	Scope *string `json:"scope,omitempty" tf:"scope,omitempty"`
}

type ServerScopeObservation struct {

	// (String) Description of the scope (permission).
	// Description of the scope (permission).
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Identifier of the resource server that the scope (permission) is associated with.
	// Identifier of the resource server that the scope (permission) is associated with.
	ResourceServerIdentifier *string `json:"resourceServerIdentifier,omitempty" tf:"resource_server_identifier,omitempty"`

	// (String) Name of the scope (permission).
	// Name of the scope (permission).
	Scope *string `json:"scope,omitempty" tf:"scope,omitempty"`
}

type ServerScopeParameters struct {

	// (String) Description of the scope (permission).
	// Description of the scope (permission).
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) Identifier of the resource server that the scope (permission) is associated with.
	// Identifier of the resource server that the scope (permission) is associated with.
	// +kubebuilder:validation:Optional
	ResourceServerIdentifier *string `json:"resourceServerIdentifier,omitempty" tf:"resource_server_identifier,omitempty"`

	// (String) Name of the scope (permission).
	// Name of the scope (permission).
	// +kubebuilder:validation:Optional
	Scope *string `json:"scope,omitempty" tf:"scope,omitempty"`
}

// ServerScopeSpec defines the desired state of ServerScope
type ServerScopeSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ServerScopeParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ServerScopeInitParameters `json:"initProvider,omitempty"`
}

// ServerScopeStatus defines the observed state of ServerScope.
type ServerScopeStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ServerScopeObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ServerScope is the Schema for the ServerScopes API. With this resource, you can manage scopes (permissions) associated with a resource server (API).
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,auth0}
type ServerScope struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.resourceServerIdentifier) || (has(self.initProvider) && has(self.initProvider.resourceServerIdentifier))",message="spec.forProvider.resourceServerIdentifier is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.scope) || (has(self.initProvider) && has(self.initProvider.scope))",message="spec.forProvider.scope is a required parameter"
	Spec   ServerScopeSpec   `json:"spec"`
	Status ServerScopeStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ServerScopeList contains a list of ServerScopes
type ServerScopeList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ServerScope `json:"items"`
}

// Repository type metadata.
var (
	ServerScope_Kind             = "ServerScope"
	ServerScope_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ServerScope_Kind}.String()
	ServerScope_KindAPIVersion   = ServerScope_Kind + "." + CRDGroupVersion.String()
	ServerScope_GroupVersionKind = CRDGroupVersion.WithKind(ServerScope_Kind)
)

func init() {
	SchemeBuilder.Register(&ServerScope{}, &ServerScopeList{})
}
