//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane-runtime/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AmazonSnsInitParameters) DeepCopyInto(out *AmazonSnsInitParameters) {
	*out = *in
	if in.AwsAccessKeyID != nil {
		in, out := &in.AwsAccessKeyID, &out.AwsAccessKeyID
		*out = new(string)
		**out = **in
	}
	if in.AwsRegion != nil {
		in, out := &in.AwsRegion, &out.AwsRegion
		*out = new(string)
		**out = **in
	}
	out.AwsSecretAccessKeySecretRef = in.AwsSecretAccessKeySecretRef
	if in.SnsAPNSPlatformApplicationArn != nil {
		in, out := &in.SnsAPNSPlatformApplicationArn, &out.SnsAPNSPlatformApplicationArn
		*out = new(string)
		**out = **in
	}
	if in.SnsGCMPlatformApplicationArn != nil {
		in, out := &in.SnsGCMPlatformApplicationArn, &out.SnsGCMPlatformApplicationArn
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AmazonSnsInitParameters.
func (in *AmazonSnsInitParameters) DeepCopy() *AmazonSnsInitParameters {
	if in == nil {
		return nil
	}
	out := new(AmazonSnsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AmazonSnsObservation) DeepCopyInto(out *AmazonSnsObservation) {
	*out = *in
	if in.AwsAccessKeyID != nil {
		in, out := &in.AwsAccessKeyID, &out.AwsAccessKeyID
		*out = new(string)
		**out = **in
	}
	if in.AwsRegion != nil {
		in, out := &in.AwsRegion, &out.AwsRegion
		*out = new(string)
		**out = **in
	}
	if in.SnsAPNSPlatformApplicationArn != nil {
		in, out := &in.SnsAPNSPlatformApplicationArn, &out.SnsAPNSPlatformApplicationArn
		*out = new(string)
		**out = **in
	}
	if in.SnsGCMPlatformApplicationArn != nil {
		in, out := &in.SnsGCMPlatformApplicationArn, &out.SnsGCMPlatformApplicationArn
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AmazonSnsObservation.
func (in *AmazonSnsObservation) DeepCopy() *AmazonSnsObservation {
	if in == nil {
		return nil
	}
	out := new(AmazonSnsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AmazonSnsParameters) DeepCopyInto(out *AmazonSnsParameters) {
	*out = *in
	if in.AwsAccessKeyID != nil {
		in, out := &in.AwsAccessKeyID, &out.AwsAccessKeyID
		*out = new(string)
		**out = **in
	}
	if in.AwsRegion != nil {
		in, out := &in.AwsRegion, &out.AwsRegion
		*out = new(string)
		**out = **in
	}
	out.AwsSecretAccessKeySecretRef = in.AwsSecretAccessKeySecretRef
	if in.SnsAPNSPlatformApplicationArn != nil {
		in, out := &in.SnsAPNSPlatformApplicationArn, &out.SnsAPNSPlatformApplicationArn
		*out = new(string)
		**out = **in
	}
	if in.SnsGCMPlatformApplicationArn != nil {
		in, out := &in.SnsGCMPlatformApplicationArn, &out.SnsGCMPlatformApplicationArn
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AmazonSnsParameters.
func (in *AmazonSnsParameters) DeepCopy() *AmazonSnsParameters {
	if in == nil {
		return nil
	}
	out := new(AmazonSnsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomAppInitParameters) DeepCopyInto(out *CustomAppInitParameters) {
	*out = *in
	if in.AppName != nil {
		in, out := &in.AppName, &out.AppName
		*out = new(string)
		**out = **in
	}
	if in.AppleAppLink != nil {
		in, out := &in.AppleAppLink, &out.AppleAppLink
		*out = new(string)
		**out = **in
	}
	if in.GoogleAppLink != nil {
		in, out := &in.GoogleAppLink, &out.GoogleAppLink
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomAppInitParameters.
func (in *CustomAppInitParameters) DeepCopy() *CustomAppInitParameters {
	if in == nil {
		return nil
	}
	out := new(CustomAppInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomAppObservation) DeepCopyInto(out *CustomAppObservation) {
	*out = *in
	if in.AppName != nil {
		in, out := &in.AppName, &out.AppName
		*out = new(string)
		**out = **in
	}
	if in.AppleAppLink != nil {
		in, out := &in.AppleAppLink, &out.AppleAppLink
		*out = new(string)
		**out = **in
	}
	if in.GoogleAppLink != nil {
		in, out := &in.GoogleAppLink, &out.GoogleAppLink
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomAppObservation.
func (in *CustomAppObservation) DeepCopy() *CustomAppObservation {
	if in == nil {
		return nil
	}
	out := new(CustomAppObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomAppParameters) DeepCopyInto(out *CustomAppParameters) {
	*out = *in
	if in.AppName != nil {
		in, out := &in.AppName, &out.AppName
		*out = new(string)
		**out = **in
	}
	if in.AppleAppLink != nil {
		in, out := &in.AppleAppLink, &out.AppleAppLink
		*out = new(string)
		**out = **in
	}
	if in.GoogleAppLink != nil {
		in, out := &in.GoogleAppLink, &out.GoogleAppLink
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomAppParameters.
func (in *CustomAppParameters) DeepCopy() *CustomAppParameters {
	if in == nil {
		return nil
	}
	out := new(CustomAppParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DirectAPNSInitParameters) DeepCopyInto(out *DirectAPNSInitParameters) {
	*out = *in
	if in.BundleID != nil {
		in, out := &in.BundleID, &out.BundleID
		*out = new(string)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	out.P12SecretRef = in.P12SecretRef
	if in.Sandbox != nil {
		in, out := &in.Sandbox, &out.Sandbox
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DirectAPNSInitParameters.
func (in *DirectAPNSInitParameters) DeepCopy() *DirectAPNSInitParameters {
	if in == nil {
		return nil
	}
	out := new(DirectAPNSInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DirectAPNSObservation) DeepCopyInto(out *DirectAPNSObservation) {
	*out = *in
	if in.BundleID != nil {
		in, out := &in.BundleID, &out.BundleID
		*out = new(string)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Sandbox != nil {
		in, out := &in.Sandbox, &out.Sandbox
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DirectAPNSObservation.
func (in *DirectAPNSObservation) DeepCopy() *DirectAPNSObservation {
	if in == nil {
		return nil
	}
	out := new(DirectAPNSObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DirectAPNSParameters) DeepCopyInto(out *DirectAPNSParameters) {
	*out = *in
	if in.BundleID != nil {
		in, out := &in.BundleID, &out.BundleID
		*out = new(string)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	out.P12SecretRef = in.P12SecretRef
	if in.Sandbox != nil {
		in, out := &in.Sandbox, &out.Sandbox
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DirectAPNSParameters.
func (in *DirectAPNSParameters) DeepCopy() *DirectAPNSParameters {
	if in == nil {
		return nil
	}
	out := new(DirectAPNSParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DirectFcmInitParameters) DeepCopyInto(out *DirectFcmInitParameters) {
	*out = *in
	out.ServerKeySecretRef = in.ServerKeySecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DirectFcmInitParameters.
func (in *DirectFcmInitParameters) DeepCopy() *DirectFcmInitParameters {
	if in == nil {
		return nil
	}
	out := new(DirectFcmInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DirectFcmObservation) DeepCopyInto(out *DirectFcmObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DirectFcmObservation.
func (in *DirectFcmObservation) DeepCopy() *DirectFcmObservation {
	if in == nil {
		return nil
	}
	out := new(DirectFcmObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DirectFcmParameters) DeepCopyInto(out *DirectFcmParameters) {
	*out = *in
	out.ServerKeySecretRef = in.ServerKeySecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DirectFcmParameters.
func (in *DirectFcmParameters) DeepCopy() *DirectFcmParameters {
	if in == nil {
		return nil
	}
	out := new(DirectFcmParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DuoInitParameters) DeepCopyInto(out *DuoInitParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Hostname != nil {
		in, out := &in.Hostname, &out.Hostname
		*out = new(string)
		**out = **in
	}
	if in.IntegrationKey != nil {
		in, out := &in.IntegrationKey, &out.IntegrationKey
		*out = new(string)
		**out = **in
	}
	if in.SecretKeySecretRef != nil {
		in, out := &in.SecretKeySecretRef, &out.SecretKeySecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DuoInitParameters.
func (in *DuoInitParameters) DeepCopy() *DuoInitParameters {
	if in == nil {
		return nil
	}
	out := new(DuoInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DuoObservation) DeepCopyInto(out *DuoObservation) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Hostname != nil {
		in, out := &in.Hostname, &out.Hostname
		*out = new(string)
		**out = **in
	}
	if in.IntegrationKey != nil {
		in, out := &in.IntegrationKey, &out.IntegrationKey
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DuoObservation.
func (in *DuoObservation) DeepCopy() *DuoObservation {
	if in == nil {
		return nil
	}
	out := new(DuoObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DuoParameters) DeepCopyInto(out *DuoParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Hostname != nil {
		in, out := &in.Hostname, &out.Hostname
		*out = new(string)
		**out = **in
	}
	if in.IntegrationKey != nil {
		in, out := &in.IntegrationKey, &out.IntegrationKey
		*out = new(string)
		**out = **in
	}
	if in.SecretKeySecretRef != nil {
		in, out := &in.SecretKeySecretRef, &out.SecretKeySecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DuoParameters.
func (in *DuoParameters) DeepCopy() *DuoParameters {
	if in == nil {
		return nil
	}
	out := new(DuoParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Guardian) DeepCopyInto(out *Guardian) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Guardian.
func (in *Guardian) DeepCopy() *Guardian {
	if in == nil {
		return nil
	}
	out := new(Guardian)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Guardian) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GuardianInitParameters) DeepCopyInto(out *GuardianInitParameters) {
	*out = *in
	if in.Duo != nil {
		in, out := &in.Duo, &out.Duo
		*out = make([]DuoInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Email != nil {
		in, out := &in.Email, &out.Email
		*out = new(bool)
		**out = **in
	}
	if in.Otp != nil {
		in, out := &in.Otp, &out.Otp
		*out = new(bool)
		**out = **in
	}
	if in.Phone != nil {
		in, out := &in.Phone, &out.Phone
		*out = make([]PhoneInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Policy != nil {
		in, out := &in.Policy, &out.Policy
		*out = new(string)
		**out = **in
	}
	if in.Push != nil {
		in, out := &in.Push, &out.Push
		*out = make([]PushInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RecoveryCode != nil {
		in, out := &in.RecoveryCode, &out.RecoveryCode
		*out = new(bool)
		**out = **in
	}
	if in.WebauthnPlatform != nil {
		in, out := &in.WebauthnPlatform, &out.WebauthnPlatform
		*out = make([]WebauthnPlatformInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.WebauthnRoaming != nil {
		in, out := &in.WebauthnRoaming, &out.WebauthnRoaming
		*out = make([]WebauthnRoamingInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GuardianInitParameters.
func (in *GuardianInitParameters) DeepCopy() *GuardianInitParameters {
	if in == nil {
		return nil
	}
	out := new(GuardianInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GuardianList) DeepCopyInto(out *GuardianList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Guardian, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GuardianList.
func (in *GuardianList) DeepCopy() *GuardianList {
	if in == nil {
		return nil
	}
	out := new(GuardianList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GuardianList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GuardianObservation) DeepCopyInto(out *GuardianObservation) {
	*out = *in
	if in.Duo != nil {
		in, out := &in.Duo, &out.Duo
		*out = make([]DuoObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Email != nil {
		in, out := &in.Email, &out.Email
		*out = new(bool)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Otp != nil {
		in, out := &in.Otp, &out.Otp
		*out = new(bool)
		**out = **in
	}
	if in.Phone != nil {
		in, out := &in.Phone, &out.Phone
		*out = make([]PhoneObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Policy != nil {
		in, out := &in.Policy, &out.Policy
		*out = new(string)
		**out = **in
	}
	if in.Push != nil {
		in, out := &in.Push, &out.Push
		*out = make([]PushObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RecoveryCode != nil {
		in, out := &in.RecoveryCode, &out.RecoveryCode
		*out = new(bool)
		**out = **in
	}
	if in.WebauthnPlatform != nil {
		in, out := &in.WebauthnPlatform, &out.WebauthnPlatform
		*out = make([]WebauthnPlatformObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.WebauthnRoaming != nil {
		in, out := &in.WebauthnRoaming, &out.WebauthnRoaming
		*out = make([]WebauthnRoamingObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GuardianObservation.
func (in *GuardianObservation) DeepCopy() *GuardianObservation {
	if in == nil {
		return nil
	}
	out := new(GuardianObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GuardianParameters) DeepCopyInto(out *GuardianParameters) {
	*out = *in
	if in.Duo != nil {
		in, out := &in.Duo, &out.Duo
		*out = make([]DuoParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Email != nil {
		in, out := &in.Email, &out.Email
		*out = new(bool)
		**out = **in
	}
	if in.Otp != nil {
		in, out := &in.Otp, &out.Otp
		*out = new(bool)
		**out = **in
	}
	if in.Phone != nil {
		in, out := &in.Phone, &out.Phone
		*out = make([]PhoneParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Policy != nil {
		in, out := &in.Policy, &out.Policy
		*out = new(string)
		**out = **in
	}
	if in.Push != nil {
		in, out := &in.Push, &out.Push
		*out = make([]PushParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RecoveryCode != nil {
		in, out := &in.RecoveryCode, &out.RecoveryCode
		*out = new(bool)
		**out = **in
	}
	if in.WebauthnPlatform != nil {
		in, out := &in.WebauthnPlatform, &out.WebauthnPlatform
		*out = make([]WebauthnPlatformParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.WebauthnRoaming != nil {
		in, out := &in.WebauthnRoaming, &out.WebauthnRoaming
		*out = make([]WebauthnRoamingParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GuardianParameters.
func (in *GuardianParameters) DeepCopy() *GuardianParameters {
	if in == nil {
		return nil
	}
	out := new(GuardianParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GuardianSpec) DeepCopyInto(out *GuardianSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GuardianSpec.
func (in *GuardianSpec) DeepCopy() *GuardianSpec {
	if in == nil {
		return nil
	}
	out := new(GuardianSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GuardianStatus) DeepCopyInto(out *GuardianStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GuardianStatus.
func (in *GuardianStatus) DeepCopy() *GuardianStatus {
	if in == nil {
		return nil
	}
	out := new(GuardianStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OptionsInitParameters) DeepCopyInto(out *OptionsInitParameters) {
	*out = *in
	if in.AuthTokenSecretRef != nil {
		in, out := &in.AuthTokenSecretRef, &out.AuthTokenSecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.EnrollmentMessage != nil {
		in, out := &in.EnrollmentMessage, &out.EnrollmentMessage
		*out = new(string)
		**out = **in
	}
	if in.From != nil {
		in, out := &in.From, &out.From
		*out = new(string)
		**out = **in
	}
	if in.MessagingServiceSid != nil {
		in, out := &in.MessagingServiceSid, &out.MessagingServiceSid
		*out = new(string)
		**out = **in
	}
	if in.Sid != nil {
		in, out := &in.Sid, &out.Sid
		*out = new(string)
		**out = **in
	}
	if in.VerificationMessage != nil {
		in, out := &in.VerificationMessage, &out.VerificationMessage
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OptionsInitParameters.
func (in *OptionsInitParameters) DeepCopy() *OptionsInitParameters {
	if in == nil {
		return nil
	}
	out := new(OptionsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OptionsObservation) DeepCopyInto(out *OptionsObservation) {
	*out = *in
	if in.EnrollmentMessage != nil {
		in, out := &in.EnrollmentMessage, &out.EnrollmentMessage
		*out = new(string)
		**out = **in
	}
	if in.From != nil {
		in, out := &in.From, &out.From
		*out = new(string)
		**out = **in
	}
	if in.MessagingServiceSid != nil {
		in, out := &in.MessagingServiceSid, &out.MessagingServiceSid
		*out = new(string)
		**out = **in
	}
	if in.Sid != nil {
		in, out := &in.Sid, &out.Sid
		*out = new(string)
		**out = **in
	}
	if in.VerificationMessage != nil {
		in, out := &in.VerificationMessage, &out.VerificationMessage
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OptionsObservation.
func (in *OptionsObservation) DeepCopy() *OptionsObservation {
	if in == nil {
		return nil
	}
	out := new(OptionsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OptionsParameters) DeepCopyInto(out *OptionsParameters) {
	*out = *in
	if in.AuthTokenSecretRef != nil {
		in, out := &in.AuthTokenSecretRef, &out.AuthTokenSecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.EnrollmentMessage != nil {
		in, out := &in.EnrollmentMessage, &out.EnrollmentMessage
		*out = new(string)
		**out = **in
	}
	if in.From != nil {
		in, out := &in.From, &out.From
		*out = new(string)
		**out = **in
	}
	if in.MessagingServiceSid != nil {
		in, out := &in.MessagingServiceSid, &out.MessagingServiceSid
		*out = new(string)
		**out = **in
	}
	if in.Sid != nil {
		in, out := &in.Sid, &out.Sid
		*out = new(string)
		**out = **in
	}
	if in.VerificationMessage != nil {
		in, out := &in.VerificationMessage, &out.VerificationMessage
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OptionsParameters.
func (in *OptionsParameters) DeepCopy() *OptionsParameters {
	if in == nil {
		return nil
	}
	out := new(OptionsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PhoneInitParameters) DeepCopyInto(out *PhoneInitParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.MessageTypes != nil {
		in, out := &in.MessageTypes, &out.MessageTypes
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Options != nil {
		in, out := &in.Options, &out.Options
		*out = make([]OptionsInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Provider != nil {
		in, out := &in.Provider, &out.Provider
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PhoneInitParameters.
func (in *PhoneInitParameters) DeepCopy() *PhoneInitParameters {
	if in == nil {
		return nil
	}
	out := new(PhoneInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PhoneObservation) DeepCopyInto(out *PhoneObservation) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.MessageTypes != nil {
		in, out := &in.MessageTypes, &out.MessageTypes
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Options != nil {
		in, out := &in.Options, &out.Options
		*out = make([]OptionsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Provider != nil {
		in, out := &in.Provider, &out.Provider
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PhoneObservation.
func (in *PhoneObservation) DeepCopy() *PhoneObservation {
	if in == nil {
		return nil
	}
	out := new(PhoneObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PhoneParameters) DeepCopyInto(out *PhoneParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.MessageTypes != nil {
		in, out := &in.MessageTypes, &out.MessageTypes
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Options != nil {
		in, out := &in.Options, &out.Options
		*out = make([]OptionsParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Provider != nil {
		in, out := &in.Provider, &out.Provider
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PhoneParameters.
func (in *PhoneParameters) DeepCopy() *PhoneParameters {
	if in == nil {
		return nil
	}
	out := new(PhoneParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PushInitParameters) DeepCopyInto(out *PushInitParameters) {
	*out = *in
	if in.AmazonSns != nil {
		in, out := &in.AmazonSns, &out.AmazonSns
		*out = make([]AmazonSnsInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CustomApp != nil {
		in, out := &in.CustomApp, &out.CustomApp
		*out = make([]CustomAppInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DirectAPNS != nil {
		in, out := &in.DirectAPNS, &out.DirectAPNS
		*out = make([]DirectAPNSInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DirectFcm != nil {
		in, out := &in.DirectFcm, &out.DirectFcm
		*out = make([]DirectFcmInitParameters, len(*in))
		copy(*out, *in)
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Provider != nil {
		in, out := &in.Provider, &out.Provider
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PushInitParameters.
func (in *PushInitParameters) DeepCopy() *PushInitParameters {
	if in == nil {
		return nil
	}
	out := new(PushInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PushObservation) DeepCopyInto(out *PushObservation) {
	*out = *in
	if in.AmazonSns != nil {
		in, out := &in.AmazonSns, &out.AmazonSns
		*out = make([]AmazonSnsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CustomApp != nil {
		in, out := &in.CustomApp, &out.CustomApp
		*out = make([]CustomAppObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DirectAPNS != nil {
		in, out := &in.DirectAPNS, &out.DirectAPNS
		*out = make([]DirectAPNSObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DirectFcm != nil {
		in, out := &in.DirectFcm, &out.DirectFcm
		*out = make([]DirectFcmParameters, len(*in))
		copy(*out, *in)
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Provider != nil {
		in, out := &in.Provider, &out.Provider
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PushObservation.
func (in *PushObservation) DeepCopy() *PushObservation {
	if in == nil {
		return nil
	}
	out := new(PushObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PushParameters) DeepCopyInto(out *PushParameters) {
	*out = *in
	if in.AmazonSns != nil {
		in, out := &in.AmazonSns, &out.AmazonSns
		*out = make([]AmazonSnsParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CustomApp != nil {
		in, out := &in.CustomApp, &out.CustomApp
		*out = make([]CustomAppParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DirectAPNS != nil {
		in, out := &in.DirectAPNS, &out.DirectAPNS
		*out = make([]DirectAPNSParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DirectFcm != nil {
		in, out := &in.DirectFcm, &out.DirectFcm
		*out = make([]DirectFcmParameters, len(*in))
		copy(*out, *in)
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Provider != nil {
		in, out := &in.Provider, &out.Provider
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PushParameters.
func (in *PushParameters) DeepCopy() *PushParameters {
	if in == nil {
		return nil
	}
	out := new(PushParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebauthnPlatformInitParameters) DeepCopyInto(out *WebauthnPlatformInitParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.OverrideRelyingParty != nil {
		in, out := &in.OverrideRelyingParty, &out.OverrideRelyingParty
		*out = new(bool)
		**out = **in
	}
	if in.RelyingPartyIdentifier != nil {
		in, out := &in.RelyingPartyIdentifier, &out.RelyingPartyIdentifier
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebauthnPlatformInitParameters.
func (in *WebauthnPlatformInitParameters) DeepCopy() *WebauthnPlatformInitParameters {
	if in == nil {
		return nil
	}
	out := new(WebauthnPlatformInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebauthnPlatformObservation) DeepCopyInto(out *WebauthnPlatformObservation) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.OverrideRelyingParty != nil {
		in, out := &in.OverrideRelyingParty, &out.OverrideRelyingParty
		*out = new(bool)
		**out = **in
	}
	if in.RelyingPartyIdentifier != nil {
		in, out := &in.RelyingPartyIdentifier, &out.RelyingPartyIdentifier
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebauthnPlatformObservation.
func (in *WebauthnPlatformObservation) DeepCopy() *WebauthnPlatformObservation {
	if in == nil {
		return nil
	}
	out := new(WebauthnPlatformObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebauthnPlatformParameters) DeepCopyInto(out *WebauthnPlatformParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.OverrideRelyingParty != nil {
		in, out := &in.OverrideRelyingParty, &out.OverrideRelyingParty
		*out = new(bool)
		**out = **in
	}
	if in.RelyingPartyIdentifier != nil {
		in, out := &in.RelyingPartyIdentifier, &out.RelyingPartyIdentifier
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebauthnPlatformParameters.
func (in *WebauthnPlatformParameters) DeepCopy() *WebauthnPlatformParameters {
	if in == nil {
		return nil
	}
	out := new(WebauthnPlatformParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebauthnRoamingInitParameters) DeepCopyInto(out *WebauthnRoamingInitParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.OverrideRelyingParty != nil {
		in, out := &in.OverrideRelyingParty, &out.OverrideRelyingParty
		*out = new(bool)
		**out = **in
	}
	if in.RelyingPartyIdentifier != nil {
		in, out := &in.RelyingPartyIdentifier, &out.RelyingPartyIdentifier
		*out = new(string)
		**out = **in
	}
	if in.UserVerification != nil {
		in, out := &in.UserVerification, &out.UserVerification
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebauthnRoamingInitParameters.
func (in *WebauthnRoamingInitParameters) DeepCopy() *WebauthnRoamingInitParameters {
	if in == nil {
		return nil
	}
	out := new(WebauthnRoamingInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebauthnRoamingObservation) DeepCopyInto(out *WebauthnRoamingObservation) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.OverrideRelyingParty != nil {
		in, out := &in.OverrideRelyingParty, &out.OverrideRelyingParty
		*out = new(bool)
		**out = **in
	}
	if in.RelyingPartyIdentifier != nil {
		in, out := &in.RelyingPartyIdentifier, &out.RelyingPartyIdentifier
		*out = new(string)
		**out = **in
	}
	if in.UserVerification != nil {
		in, out := &in.UserVerification, &out.UserVerification
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebauthnRoamingObservation.
func (in *WebauthnRoamingObservation) DeepCopy() *WebauthnRoamingObservation {
	if in == nil {
		return nil
	}
	out := new(WebauthnRoamingObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebauthnRoamingParameters) DeepCopyInto(out *WebauthnRoamingParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.OverrideRelyingParty != nil {
		in, out := &in.OverrideRelyingParty, &out.OverrideRelyingParty
		*out = new(bool)
		**out = **in
	}
	if in.RelyingPartyIdentifier != nil {
		in, out := &in.RelyingPartyIdentifier, &out.RelyingPartyIdentifier
		*out = new(string)
		**out = **in
	}
	if in.UserVerification != nil {
		in, out := &in.UserVerification, &out.UserVerification
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebauthnRoamingParameters.
func (in *WebauthnRoamingParameters) DeepCopy() *WebauthnRoamingParameters {
	if in == nil {
		return nil
	}
	out := new(WebauthnRoamingParameters)
	in.DeepCopyInto(out)
	return out
}
