apiVersion: ruleconfig.auth0.jwefers.upbound.io/v1alpha1
kind: Config
metadata:
  annotations:
    meta.upbound.io/example-id: ruleconfig/v1alpha1/config
  labels:
    testing.upbound.io/example-name: my_rule_config
  name: my-rule-config
spec:
  forProvider:
    key: foo
    valueSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system

---

apiVersion: rule.auth0.jwefers.upbound.io/v1alpha1
kind: Rule
metadata:
  annotations:
    meta.upbound.io/example-id: ruleconfig/v1alpha1/config
  labels:
    testing.upbound.io/example-name: my_rule
  name: my-rule
spec:
  forProvider:
    enabled: true
    name: empty-rule
    script: |2
          function (user, context, callback) {
            callback(null, user, context);
          }
