apiVersion: clientcredentials.auth0.jwefers.upbound.io/v1alpha1
kind: Credentials
metadata:
  annotations:
    meta.upbound.io/example-id: clientcredentials/v1alpha1/credentials
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    authenticationMethod: client_secret_post
    clientId: ${auth0_client.my_client.id}

---

apiVersion: client.auth0.jwefers.upbound.io/v1alpha1
kind: Client
metadata:
  annotations:
    meta.upbound.io/example-id: clientcredentials/v1alpha1/credentials
  labels:
    testing.upbound.io/example-name: my_client
  name: my-client
spec:
  forProvider:
    appType: non_interactive
    jwtConfiguration:
    - alg: RS256
    name: Application - Acceptance Test
