//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MappingInitParameters) DeepCopyInto(out *MappingInitParameters) {
	*out = *in
	if in.Auth0 != nil {
		in, out := &in.Auth0, &out.Auth0
		*out = new(string)
		**out = **in
	}
	if in.Scim != nil {
		in, out := &in.Scim, &out.Scim
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MappingInitParameters.
func (in *MappingInitParameters) DeepCopy() *MappingInitParameters {
	if in == nil {
		return nil
	}
	out := new(MappingInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MappingObservation) DeepCopyInto(out *MappingObservation) {
	*out = *in
	if in.Auth0 != nil {
		in, out := &in.Auth0, &out.Auth0
		*out = new(string)
		**out = **in
	}
	if in.Scim != nil {
		in, out := &in.Scim, &out.Scim
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MappingObservation.
func (in *MappingObservation) DeepCopy() *MappingObservation {
	if in == nil {
		return nil
	}
	out := new(MappingObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MappingParameters) DeepCopyInto(out *MappingParameters) {
	*out = *in
	if in.Auth0 != nil {
		in, out := &in.Auth0, &out.Auth0
		*out = new(string)
		**out = **in
	}
	if in.Scim != nil {
		in, out := &in.Scim, &out.Scim
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MappingParameters.
func (in *MappingParameters) DeepCopy() *MappingParameters {
	if in == nil {
		return nil
	}
	out := new(MappingParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScimConfiguration) DeepCopyInto(out *ScimConfiguration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScimConfiguration.
func (in *ScimConfiguration) DeepCopy() *ScimConfiguration {
	if in == nil {
		return nil
	}
	out := new(ScimConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ScimConfiguration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScimConfigurationInitParameters) DeepCopyInto(out *ScimConfigurationInitParameters) {
	*out = *in
	if in.ConnectionID != nil {
		in, out := &in.ConnectionID, &out.ConnectionID
		*out = new(string)
		**out = **in
	}
	if in.Mapping != nil {
		in, out := &in.Mapping, &out.Mapping
		*out = make([]MappingInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.UserIDAttribute != nil {
		in, out := &in.UserIDAttribute, &out.UserIDAttribute
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScimConfigurationInitParameters.
func (in *ScimConfigurationInitParameters) DeepCopy() *ScimConfigurationInitParameters {
	if in == nil {
		return nil
	}
	out := new(ScimConfigurationInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScimConfigurationList) DeepCopyInto(out *ScimConfigurationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ScimConfiguration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScimConfigurationList.
func (in *ScimConfigurationList) DeepCopy() *ScimConfigurationList {
	if in == nil {
		return nil
	}
	out := new(ScimConfigurationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ScimConfigurationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScimConfigurationObservation) DeepCopyInto(out *ScimConfigurationObservation) {
	*out = *in
	if in.ConnectionID != nil {
		in, out := &in.ConnectionID, &out.ConnectionID
		*out = new(string)
		**out = **in
	}
	if in.ConnectionName != nil {
		in, out := &in.ConnectionName, &out.ConnectionName
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Mapping != nil {
		in, out := &in.Mapping, &out.Mapping
		*out = make([]MappingObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Strategy != nil {
		in, out := &in.Strategy, &out.Strategy
		*out = new(string)
		**out = **in
	}
	if in.TenantName != nil {
		in, out := &in.TenantName, &out.TenantName
		*out = new(string)
		**out = **in
	}
	if in.UserIDAttribute != nil {
		in, out := &in.UserIDAttribute, &out.UserIDAttribute
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScimConfigurationObservation.
func (in *ScimConfigurationObservation) DeepCopy() *ScimConfigurationObservation {
	if in == nil {
		return nil
	}
	out := new(ScimConfigurationObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScimConfigurationParameters) DeepCopyInto(out *ScimConfigurationParameters) {
	*out = *in
	if in.ConnectionID != nil {
		in, out := &in.ConnectionID, &out.ConnectionID
		*out = new(string)
		**out = **in
	}
	if in.Mapping != nil {
		in, out := &in.Mapping, &out.Mapping
		*out = make([]MappingParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.UserIDAttribute != nil {
		in, out := &in.UserIDAttribute, &out.UserIDAttribute
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScimConfigurationParameters.
func (in *ScimConfigurationParameters) DeepCopy() *ScimConfigurationParameters {
	if in == nil {
		return nil
	}
	out := new(ScimConfigurationParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScimConfigurationSpec) DeepCopyInto(out *ScimConfigurationSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScimConfigurationSpec.
func (in *ScimConfigurationSpec) DeepCopy() *ScimConfigurationSpec {
	if in == nil {
		return nil
	}
	out := new(ScimConfigurationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScimConfigurationStatus) DeepCopyInto(out *ScimConfigurationStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScimConfigurationStatus.
func (in *ScimConfigurationStatus) DeepCopy() *ScimConfigurationStatus {
	if in == nil {
		return nil
	}
	out := new(ScimConfigurationStatus)
	in.DeepCopyInto(out)
	return out
}
