apiVersion: pages.auth0.com/v1alpha1
kind: Pages
metadata:
  annotations:
    meta.upbound.io/example-id: pages/v1alpha1/pages
  labels:
    testing.upbound.io/example-name: my_pages
  name: my-pages
spec:
  forProvider:
    changePassword:
    - enabled: true
      html: <html><body>My Custom Reset Password Page</body></html>
    error:
    - html: <html><body>My Custom Error Page</body></html>
      showLogLink: true
      url: https://example.com
    guardianMfa:
    - enabled: true
      html: <html><body>My Custom MFA Page</body></html>
    login:
    - enabled: true
      html: <html><body>My Custom Login Page</body></html>
