//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlagsInitParameters) DeepCopyInto(out *FlagsInitParameters) {
	*out = *in
	if in.AllowLegacyDelegationGrantTypes != nil {
		in, out := &in.AllowLegacyDelegationGrantTypes, &out.AllowLegacyDelegationGrantTypes
		*out = new(bool)
		**out = **in
	}
	if in.AllowLegacyRoGrantTypes != nil {
		in, out := &in.AllowLegacyRoGrantTypes, &out.AllowLegacyRoGrantTypes
		*out = new(bool)
		**out = **in
	}
	if in.AllowLegacyTokeninfoEndpoint != nil {
		in, out := &in.AllowLegacyTokeninfoEndpoint, &out.AllowLegacyTokeninfoEndpoint
		*out = new(bool)
		**out = **in
	}
	if in.DashboardInsightsView != nil {
		in, out := &in.DashboardInsightsView, &out.DashboardInsightsView
		*out = new(bool)
		**out = **in
	}
	if in.DashboardLogStreamsNext != nil {
		in, out := &in.DashboardLogStreamsNext, &out.DashboardLogStreamsNext
		*out = new(bool)
		**out = **in
	}
	if in.DisableClickjackProtectionHeaders != nil {
		in, out := &in.DisableClickjackProtectionHeaders, &out.DisableClickjackProtectionHeaders
		*out = new(bool)
		**out = **in
	}
	if in.DisableFieldsMapFix != nil {
		in, out := &in.DisableFieldsMapFix, &out.DisableFieldsMapFix
		*out = new(bool)
		**out = **in
	}
	if in.DisableManagementAPISMSObfuscation != nil {
		in, out := &in.DisableManagementAPISMSObfuscation, &out.DisableManagementAPISMSObfuscation
		*out = new(bool)
		**out = **in
	}
	if in.EnableAdfsWaadEmailVerification != nil {
		in, out := &in.EnableAdfsWaadEmailVerification, &out.EnableAdfsWaadEmailVerification
		*out = new(bool)
		**out = **in
	}
	if in.EnableApisSection != nil {
		in, out := &in.EnableApisSection, &out.EnableApisSection
		*out = new(bool)
		**out = **in
	}
	if in.EnableClientConnections != nil {
		in, out := &in.EnableClientConnections, &out.EnableClientConnections
		*out = new(bool)
		**out = **in
	}
	if in.EnableCustomDomainInEmails != nil {
		in, out := &in.EnableCustomDomainInEmails, &out.EnableCustomDomainInEmails
		*out = new(bool)
		**out = **in
	}
	if in.EnableDynamicClientRegistration != nil {
		in, out := &in.EnableDynamicClientRegistration, &out.EnableDynamicClientRegistration
		*out = new(bool)
		**out = **in
	}
	if in.EnableIdtokenApi2 != nil {
		in, out := &in.EnableIdtokenApi2, &out.EnableIdtokenApi2
		*out = new(bool)
		**out = **in
	}
	if in.EnableLegacyLogsSearchV2 != nil {
		in, out := &in.EnableLegacyLogsSearchV2, &out.EnableLegacyLogsSearchV2
		*out = new(bool)
		**out = **in
	}
	if in.EnableLegacyProfile != nil {
		in, out := &in.EnableLegacyProfile, &out.EnableLegacyProfile
		*out = new(bool)
		**out = **in
	}
	if in.EnablePipeline2 != nil {
		in, out := &in.EnablePipeline2, &out.EnablePipeline2
		*out = new(bool)
		**out = **in
	}
	if in.EnablePublicSignupUserExistsError != nil {
		in, out := &in.EnablePublicSignupUserExistsError, &out.EnablePublicSignupUserExistsError
		*out = new(bool)
		**out = **in
	}
	if in.EnableSso != nil {
		in, out := &in.EnableSso, &out.EnableSso
		*out = new(bool)
		**out = **in
	}
	if in.MfaShowFactorListOnEnrollment != nil {
		in, out := &in.MfaShowFactorListOnEnrollment, &out.MfaShowFactorListOnEnrollment
		*out = new(bool)
		**out = **in
	}
	if in.NoDiscloseEnterpriseConnections != nil {
		in, out := &in.NoDiscloseEnterpriseConnections, &out.NoDiscloseEnterpriseConnections
		*out = new(bool)
		**out = **in
	}
	if in.RemoveAlgFromJwks != nil {
		in, out := &in.RemoveAlgFromJwks, &out.RemoveAlgFromJwks
		*out = new(bool)
		**out = **in
	}
	if in.RequirePushedAuthorizationRequests != nil {
		in, out := &in.RequirePushedAuthorizationRequests, &out.RequirePushedAuthorizationRequests
		*out = new(bool)
		**out = **in
	}
	if in.RevokeRefreshTokenGrant != nil {
		in, out := &in.RevokeRefreshTokenGrant, &out.RevokeRefreshTokenGrant
		*out = new(bool)
		**out = **in
	}
	if in.UseScopeDescriptionsForConsent != nil {
		in, out := &in.UseScopeDescriptionsForConsent, &out.UseScopeDescriptionsForConsent
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlagsInitParameters.
func (in *FlagsInitParameters) DeepCopy() *FlagsInitParameters {
	if in == nil {
		return nil
	}
	out := new(FlagsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlagsObservation) DeepCopyInto(out *FlagsObservation) {
	*out = *in
	if in.AllowLegacyDelegationGrantTypes != nil {
		in, out := &in.AllowLegacyDelegationGrantTypes, &out.AllowLegacyDelegationGrantTypes
		*out = new(bool)
		**out = **in
	}
	if in.AllowLegacyRoGrantTypes != nil {
		in, out := &in.AllowLegacyRoGrantTypes, &out.AllowLegacyRoGrantTypes
		*out = new(bool)
		**out = **in
	}
	if in.AllowLegacyTokeninfoEndpoint != nil {
		in, out := &in.AllowLegacyTokeninfoEndpoint, &out.AllowLegacyTokeninfoEndpoint
		*out = new(bool)
		**out = **in
	}
	if in.DashboardInsightsView != nil {
		in, out := &in.DashboardInsightsView, &out.DashboardInsightsView
		*out = new(bool)
		**out = **in
	}
	if in.DashboardLogStreamsNext != nil {
		in, out := &in.DashboardLogStreamsNext, &out.DashboardLogStreamsNext
		*out = new(bool)
		**out = **in
	}
	if in.DisableClickjackProtectionHeaders != nil {
		in, out := &in.DisableClickjackProtectionHeaders, &out.DisableClickjackProtectionHeaders
		*out = new(bool)
		**out = **in
	}
	if in.DisableFieldsMapFix != nil {
		in, out := &in.DisableFieldsMapFix, &out.DisableFieldsMapFix
		*out = new(bool)
		**out = **in
	}
	if in.DisableManagementAPISMSObfuscation != nil {
		in, out := &in.DisableManagementAPISMSObfuscation, &out.DisableManagementAPISMSObfuscation
		*out = new(bool)
		**out = **in
	}
	if in.EnableAdfsWaadEmailVerification != nil {
		in, out := &in.EnableAdfsWaadEmailVerification, &out.EnableAdfsWaadEmailVerification
		*out = new(bool)
		**out = **in
	}
	if in.EnableApisSection != nil {
		in, out := &in.EnableApisSection, &out.EnableApisSection
		*out = new(bool)
		**out = **in
	}
	if in.EnableClientConnections != nil {
		in, out := &in.EnableClientConnections, &out.EnableClientConnections
		*out = new(bool)
		**out = **in
	}
	if in.EnableCustomDomainInEmails != nil {
		in, out := &in.EnableCustomDomainInEmails, &out.EnableCustomDomainInEmails
		*out = new(bool)
		**out = **in
	}
	if in.EnableDynamicClientRegistration != nil {
		in, out := &in.EnableDynamicClientRegistration, &out.EnableDynamicClientRegistration
		*out = new(bool)
		**out = **in
	}
	if in.EnableIdtokenApi2 != nil {
		in, out := &in.EnableIdtokenApi2, &out.EnableIdtokenApi2
		*out = new(bool)
		**out = **in
	}
	if in.EnableLegacyLogsSearchV2 != nil {
		in, out := &in.EnableLegacyLogsSearchV2, &out.EnableLegacyLogsSearchV2
		*out = new(bool)
		**out = **in
	}
	if in.EnableLegacyProfile != nil {
		in, out := &in.EnableLegacyProfile, &out.EnableLegacyProfile
		*out = new(bool)
		**out = **in
	}
	if in.EnablePipeline2 != nil {
		in, out := &in.EnablePipeline2, &out.EnablePipeline2
		*out = new(bool)
		**out = **in
	}
	if in.EnablePublicSignupUserExistsError != nil {
		in, out := &in.EnablePublicSignupUserExistsError, &out.EnablePublicSignupUserExistsError
		*out = new(bool)
		**out = **in
	}
	if in.EnableSso != nil {
		in, out := &in.EnableSso, &out.EnableSso
		*out = new(bool)
		**out = **in
	}
	if in.MfaShowFactorListOnEnrollment != nil {
		in, out := &in.MfaShowFactorListOnEnrollment, &out.MfaShowFactorListOnEnrollment
		*out = new(bool)
		**out = **in
	}
	if in.NoDiscloseEnterpriseConnections != nil {
		in, out := &in.NoDiscloseEnterpriseConnections, &out.NoDiscloseEnterpriseConnections
		*out = new(bool)
		**out = **in
	}
	if in.RemoveAlgFromJwks != nil {
		in, out := &in.RemoveAlgFromJwks, &out.RemoveAlgFromJwks
		*out = new(bool)
		**out = **in
	}
	if in.RequirePushedAuthorizationRequests != nil {
		in, out := &in.RequirePushedAuthorizationRequests, &out.RequirePushedAuthorizationRequests
		*out = new(bool)
		**out = **in
	}
	if in.RevokeRefreshTokenGrant != nil {
		in, out := &in.RevokeRefreshTokenGrant, &out.RevokeRefreshTokenGrant
		*out = new(bool)
		**out = **in
	}
	if in.UseScopeDescriptionsForConsent != nil {
		in, out := &in.UseScopeDescriptionsForConsent, &out.UseScopeDescriptionsForConsent
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlagsObservation.
func (in *FlagsObservation) DeepCopy() *FlagsObservation {
	if in == nil {
		return nil
	}
	out := new(FlagsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlagsParameters) DeepCopyInto(out *FlagsParameters) {
	*out = *in
	if in.AllowLegacyDelegationGrantTypes != nil {
		in, out := &in.AllowLegacyDelegationGrantTypes, &out.AllowLegacyDelegationGrantTypes
		*out = new(bool)
		**out = **in
	}
	if in.AllowLegacyRoGrantTypes != nil {
		in, out := &in.AllowLegacyRoGrantTypes, &out.AllowLegacyRoGrantTypes
		*out = new(bool)
		**out = **in
	}
	if in.AllowLegacyTokeninfoEndpoint != nil {
		in, out := &in.AllowLegacyTokeninfoEndpoint, &out.AllowLegacyTokeninfoEndpoint
		*out = new(bool)
		**out = **in
	}
	if in.DashboardInsightsView != nil {
		in, out := &in.DashboardInsightsView, &out.DashboardInsightsView
		*out = new(bool)
		**out = **in
	}
	if in.DashboardLogStreamsNext != nil {
		in, out := &in.DashboardLogStreamsNext, &out.DashboardLogStreamsNext
		*out = new(bool)
		**out = **in
	}
	if in.DisableClickjackProtectionHeaders != nil {
		in, out := &in.DisableClickjackProtectionHeaders, &out.DisableClickjackProtectionHeaders
		*out = new(bool)
		**out = **in
	}
	if in.DisableFieldsMapFix != nil {
		in, out := &in.DisableFieldsMapFix, &out.DisableFieldsMapFix
		*out = new(bool)
		**out = **in
	}
	if in.DisableManagementAPISMSObfuscation != nil {
		in, out := &in.DisableManagementAPISMSObfuscation, &out.DisableManagementAPISMSObfuscation
		*out = new(bool)
		**out = **in
	}
	if in.EnableAdfsWaadEmailVerification != nil {
		in, out := &in.EnableAdfsWaadEmailVerification, &out.EnableAdfsWaadEmailVerification
		*out = new(bool)
		**out = **in
	}
	if in.EnableApisSection != nil {
		in, out := &in.EnableApisSection, &out.EnableApisSection
		*out = new(bool)
		**out = **in
	}
	if in.EnableClientConnections != nil {
		in, out := &in.EnableClientConnections, &out.EnableClientConnections
		*out = new(bool)
		**out = **in
	}
	if in.EnableCustomDomainInEmails != nil {
		in, out := &in.EnableCustomDomainInEmails, &out.EnableCustomDomainInEmails
		*out = new(bool)
		**out = **in
	}
	if in.EnableDynamicClientRegistration != nil {
		in, out := &in.EnableDynamicClientRegistration, &out.EnableDynamicClientRegistration
		*out = new(bool)
		**out = **in
	}
	if in.EnableIdtokenApi2 != nil {
		in, out := &in.EnableIdtokenApi2, &out.EnableIdtokenApi2
		*out = new(bool)
		**out = **in
	}
	if in.EnableLegacyLogsSearchV2 != nil {
		in, out := &in.EnableLegacyLogsSearchV2, &out.EnableLegacyLogsSearchV2
		*out = new(bool)
		**out = **in
	}
	if in.EnableLegacyProfile != nil {
		in, out := &in.EnableLegacyProfile, &out.EnableLegacyProfile
		*out = new(bool)
		**out = **in
	}
	if in.EnablePipeline2 != nil {
		in, out := &in.EnablePipeline2, &out.EnablePipeline2
		*out = new(bool)
		**out = **in
	}
	if in.EnablePublicSignupUserExistsError != nil {
		in, out := &in.EnablePublicSignupUserExistsError, &out.EnablePublicSignupUserExistsError
		*out = new(bool)
		**out = **in
	}
	if in.EnableSso != nil {
		in, out := &in.EnableSso, &out.EnableSso
		*out = new(bool)
		**out = **in
	}
	if in.MfaShowFactorListOnEnrollment != nil {
		in, out := &in.MfaShowFactorListOnEnrollment, &out.MfaShowFactorListOnEnrollment
		*out = new(bool)
		**out = **in
	}
	if in.NoDiscloseEnterpriseConnections != nil {
		in, out := &in.NoDiscloseEnterpriseConnections, &out.NoDiscloseEnterpriseConnections
		*out = new(bool)
		**out = **in
	}
	if in.RemoveAlgFromJwks != nil {
		in, out := &in.RemoveAlgFromJwks, &out.RemoveAlgFromJwks
		*out = new(bool)
		**out = **in
	}
	if in.RequirePushedAuthorizationRequests != nil {
		in, out := &in.RequirePushedAuthorizationRequests, &out.RequirePushedAuthorizationRequests
		*out = new(bool)
		**out = **in
	}
	if in.RevokeRefreshTokenGrant != nil {
		in, out := &in.RevokeRefreshTokenGrant, &out.RevokeRefreshTokenGrant
		*out = new(bool)
		**out = **in
	}
	if in.UseScopeDescriptionsForConsent != nil {
		in, out := &in.UseScopeDescriptionsForConsent, &out.UseScopeDescriptionsForConsent
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlagsParameters.
func (in *FlagsParameters) DeepCopy() *FlagsParameters {
	if in == nil {
		return nil
	}
	out := new(FlagsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MtlsInitParameters) DeepCopyInto(out *MtlsInitParameters) {
	*out = *in
	if in.Disable != nil {
		in, out := &in.Disable, &out.Disable
		*out = new(bool)
		**out = **in
	}
	if in.EnableEndpointAliases != nil {
		in, out := &in.EnableEndpointAliases, &out.EnableEndpointAliases
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MtlsInitParameters.
func (in *MtlsInitParameters) DeepCopy() *MtlsInitParameters {
	if in == nil {
		return nil
	}
	out := new(MtlsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MtlsObservation) DeepCopyInto(out *MtlsObservation) {
	*out = *in
	if in.Disable != nil {
		in, out := &in.Disable, &out.Disable
		*out = new(bool)
		**out = **in
	}
	if in.EnableEndpointAliases != nil {
		in, out := &in.EnableEndpointAliases, &out.EnableEndpointAliases
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MtlsObservation.
func (in *MtlsObservation) DeepCopy() *MtlsObservation {
	if in == nil {
		return nil
	}
	out := new(MtlsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MtlsParameters) DeepCopyInto(out *MtlsParameters) {
	*out = *in
	if in.Disable != nil {
		in, out := &in.Disable, &out.Disable
		*out = new(bool)
		**out = **in
	}
	if in.EnableEndpointAliases != nil {
		in, out := &in.EnableEndpointAliases, &out.EnableEndpointAliases
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MtlsParameters.
func (in *MtlsParameters) DeepCopy() *MtlsParameters {
	if in == nil {
		return nil
	}
	out := new(MtlsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SessionCookieInitParameters) DeepCopyInto(out *SessionCookieInitParameters) {
	*out = *in
	if in.Mode != nil {
		in, out := &in.Mode, &out.Mode
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SessionCookieInitParameters.
func (in *SessionCookieInitParameters) DeepCopy() *SessionCookieInitParameters {
	if in == nil {
		return nil
	}
	out := new(SessionCookieInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SessionCookieObservation) DeepCopyInto(out *SessionCookieObservation) {
	*out = *in
	if in.Mode != nil {
		in, out := &in.Mode, &out.Mode
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SessionCookieObservation.
func (in *SessionCookieObservation) DeepCopy() *SessionCookieObservation {
	if in == nil {
		return nil
	}
	out := new(SessionCookieObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SessionCookieParameters) DeepCopyInto(out *SessionCookieParameters) {
	*out = *in
	if in.Mode != nil {
		in, out := &in.Mode, &out.Mode
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SessionCookieParameters.
func (in *SessionCookieParameters) DeepCopy() *SessionCookieParameters {
	if in == nil {
		return nil
	}
	out := new(SessionCookieParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SessionsInitParameters) DeepCopyInto(out *SessionsInitParameters) {
	*out = *in
	if in.OidcLogoutPromptEnabled != nil {
		in, out := &in.OidcLogoutPromptEnabled, &out.OidcLogoutPromptEnabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SessionsInitParameters.
func (in *SessionsInitParameters) DeepCopy() *SessionsInitParameters {
	if in == nil {
		return nil
	}
	out := new(SessionsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SessionsObservation) DeepCopyInto(out *SessionsObservation) {
	*out = *in
	if in.OidcLogoutPromptEnabled != nil {
		in, out := &in.OidcLogoutPromptEnabled, &out.OidcLogoutPromptEnabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SessionsObservation.
func (in *SessionsObservation) DeepCopy() *SessionsObservation {
	if in == nil {
		return nil
	}
	out := new(SessionsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SessionsParameters) DeepCopyInto(out *SessionsParameters) {
	*out = *in
	if in.OidcLogoutPromptEnabled != nil {
		in, out := &in.OidcLogoutPromptEnabled, &out.OidcLogoutPromptEnabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SessionsParameters.
func (in *SessionsParameters) DeepCopy() *SessionsParameters {
	if in == nil {
		return nil
	}
	out := new(SessionsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Tenant) DeepCopyInto(out *Tenant) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Tenant.
func (in *Tenant) DeepCopy() *Tenant {
	if in == nil {
		return nil
	}
	out := new(Tenant)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Tenant) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantInitParameters) DeepCopyInto(out *TenantInitParameters) {
	*out = *in
	if in.AcrValuesSupported != nil {
		in, out := &in.AcrValuesSupported, &out.AcrValuesSupported
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.AllowOrganizationNameInAuthenticationAPI != nil {
		in, out := &in.AllowOrganizationNameInAuthenticationAPI, &out.AllowOrganizationNameInAuthenticationAPI
		*out = new(bool)
		**out = **in
	}
	if in.AllowedLogoutUrls != nil {
		in, out := &in.AllowedLogoutUrls, &out.AllowedLogoutUrls
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.CustomizeMfaInPostloginAction != nil {
		in, out := &in.CustomizeMfaInPostloginAction, &out.CustomizeMfaInPostloginAction
		*out = new(bool)
		**out = **in
	}
	if in.DefaultAudience != nil {
		in, out := &in.DefaultAudience, &out.DefaultAudience
		*out = new(string)
		**out = **in
	}
	if in.DefaultDirectory != nil {
		in, out := &in.DefaultDirectory, &out.DefaultDirectory
		*out = new(string)
		**out = **in
	}
	if in.DefaultRedirectionURI != nil {
		in, out := &in.DefaultRedirectionURI, &out.DefaultRedirectionURI
		*out = new(string)
		**out = **in
	}
	if in.DisableAcrValuesSupported != nil {
		in, out := &in.DisableAcrValuesSupported, &out.DisableAcrValuesSupported
		*out = new(bool)
		**out = **in
	}
	if in.EnabledLocales != nil {
		in, out := &in.EnabledLocales, &out.EnabledLocales
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Flags != nil {
		in, out := &in.Flags, &out.Flags
		*out = make([]FlagsInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.FriendlyName != nil {
		in, out := &in.FriendlyName, &out.FriendlyName
		*out = new(string)
		**out = **in
	}
	if in.IdleSessionLifetime != nil {
		in, out := &in.IdleSessionLifetime, &out.IdleSessionLifetime
		*out = new(float64)
		**out = **in
	}
	if in.Mtls != nil {
		in, out := &in.Mtls, &out.Mtls
		*out = make([]MtlsInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PictureURL != nil {
		in, out := &in.PictureURL, &out.PictureURL
		*out = new(string)
		**out = **in
	}
	if in.PushedAuthorizationRequestsSupported != nil {
		in, out := &in.PushedAuthorizationRequestsSupported, &out.PushedAuthorizationRequestsSupported
		*out = new(bool)
		**out = **in
	}
	if in.SandboxVersion != nil {
		in, out := &in.SandboxVersion, &out.SandboxVersion
		*out = new(string)
		**out = **in
	}
	if in.SessionCookie != nil {
		in, out := &in.SessionCookie, &out.SessionCookie
		*out = make([]SessionCookieInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SessionLifetime != nil {
		in, out := &in.SessionLifetime, &out.SessionLifetime
		*out = new(float64)
		**out = **in
	}
	if in.Sessions != nil {
		in, out := &in.Sessions, &out.Sessions
		*out = make([]SessionsInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SupportEmail != nil {
		in, out := &in.SupportEmail, &out.SupportEmail
		*out = new(string)
		**out = **in
	}
	if in.SupportURL != nil {
		in, out := &in.SupportURL, &out.SupportURL
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantInitParameters.
func (in *TenantInitParameters) DeepCopy() *TenantInitParameters {
	if in == nil {
		return nil
	}
	out := new(TenantInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantList) DeepCopyInto(out *TenantList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Tenant, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantList.
func (in *TenantList) DeepCopy() *TenantList {
	if in == nil {
		return nil
	}
	out := new(TenantList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TenantList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantObservation) DeepCopyInto(out *TenantObservation) {
	*out = *in
	if in.AcrValuesSupported != nil {
		in, out := &in.AcrValuesSupported, &out.AcrValuesSupported
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.AllowOrganizationNameInAuthenticationAPI != nil {
		in, out := &in.AllowOrganizationNameInAuthenticationAPI, &out.AllowOrganizationNameInAuthenticationAPI
		*out = new(bool)
		**out = **in
	}
	if in.AllowedLogoutUrls != nil {
		in, out := &in.AllowedLogoutUrls, &out.AllowedLogoutUrls
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.CustomizeMfaInPostloginAction != nil {
		in, out := &in.CustomizeMfaInPostloginAction, &out.CustomizeMfaInPostloginAction
		*out = new(bool)
		**out = **in
	}
	if in.DefaultAudience != nil {
		in, out := &in.DefaultAudience, &out.DefaultAudience
		*out = new(string)
		**out = **in
	}
	if in.DefaultDirectory != nil {
		in, out := &in.DefaultDirectory, &out.DefaultDirectory
		*out = new(string)
		**out = **in
	}
	if in.DefaultRedirectionURI != nil {
		in, out := &in.DefaultRedirectionURI, &out.DefaultRedirectionURI
		*out = new(string)
		**out = **in
	}
	if in.DisableAcrValuesSupported != nil {
		in, out := &in.DisableAcrValuesSupported, &out.DisableAcrValuesSupported
		*out = new(bool)
		**out = **in
	}
	if in.EnabledLocales != nil {
		in, out := &in.EnabledLocales, &out.EnabledLocales
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Flags != nil {
		in, out := &in.Flags, &out.Flags
		*out = make([]FlagsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.FriendlyName != nil {
		in, out := &in.FriendlyName, &out.FriendlyName
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.IdleSessionLifetime != nil {
		in, out := &in.IdleSessionLifetime, &out.IdleSessionLifetime
		*out = new(float64)
		**out = **in
	}
	if in.Mtls != nil {
		in, out := &in.Mtls, &out.Mtls
		*out = make([]MtlsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PictureURL != nil {
		in, out := &in.PictureURL, &out.PictureURL
		*out = new(string)
		**out = **in
	}
	if in.PushedAuthorizationRequestsSupported != nil {
		in, out := &in.PushedAuthorizationRequestsSupported, &out.PushedAuthorizationRequestsSupported
		*out = new(bool)
		**out = **in
	}
	if in.SandboxVersion != nil {
		in, out := &in.SandboxVersion, &out.SandboxVersion
		*out = new(string)
		**out = **in
	}
	if in.SessionCookie != nil {
		in, out := &in.SessionCookie, &out.SessionCookie
		*out = make([]SessionCookieObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SessionLifetime != nil {
		in, out := &in.SessionLifetime, &out.SessionLifetime
		*out = new(float64)
		**out = **in
	}
	if in.Sessions != nil {
		in, out := &in.Sessions, &out.Sessions
		*out = make([]SessionsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SupportEmail != nil {
		in, out := &in.SupportEmail, &out.SupportEmail
		*out = new(string)
		**out = **in
	}
	if in.SupportURL != nil {
		in, out := &in.SupportURL, &out.SupportURL
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantObservation.
func (in *TenantObservation) DeepCopy() *TenantObservation {
	if in == nil {
		return nil
	}
	out := new(TenantObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantParameters) DeepCopyInto(out *TenantParameters) {
	*out = *in
	if in.AcrValuesSupported != nil {
		in, out := &in.AcrValuesSupported, &out.AcrValuesSupported
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.AllowOrganizationNameInAuthenticationAPI != nil {
		in, out := &in.AllowOrganizationNameInAuthenticationAPI, &out.AllowOrganizationNameInAuthenticationAPI
		*out = new(bool)
		**out = **in
	}
	if in.AllowedLogoutUrls != nil {
		in, out := &in.AllowedLogoutUrls, &out.AllowedLogoutUrls
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.CustomizeMfaInPostloginAction != nil {
		in, out := &in.CustomizeMfaInPostloginAction, &out.CustomizeMfaInPostloginAction
		*out = new(bool)
		**out = **in
	}
	if in.DefaultAudience != nil {
		in, out := &in.DefaultAudience, &out.DefaultAudience
		*out = new(string)
		**out = **in
	}
	if in.DefaultDirectory != nil {
		in, out := &in.DefaultDirectory, &out.DefaultDirectory
		*out = new(string)
		**out = **in
	}
	if in.DefaultRedirectionURI != nil {
		in, out := &in.DefaultRedirectionURI, &out.DefaultRedirectionURI
		*out = new(string)
		**out = **in
	}
	if in.DisableAcrValuesSupported != nil {
		in, out := &in.DisableAcrValuesSupported, &out.DisableAcrValuesSupported
		*out = new(bool)
		**out = **in
	}
	if in.EnabledLocales != nil {
		in, out := &in.EnabledLocales, &out.EnabledLocales
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Flags != nil {
		in, out := &in.Flags, &out.Flags
		*out = make([]FlagsParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.FriendlyName != nil {
		in, out := &in.FriendlyName, &out.FriendlyName
		*out = new(string)
		**out = **in
	}
	if in.IdleSessionLifetime != nil {
		in, out := &in.IdleSessionLifetime, &out.IdleSessionLifetime
		*out = new(float64)
		**out = **in
	}
	if in.Mtls != nil {
		in, out := &in.Mtls, &out.Mtls
		*out = make([]MtlsParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PictureURL != nil {
		in, out := &in.PictureURL, &out.PictureURL
		*out = new(string)
		**out = **in
	}
	if in.PushedAuthorizationRequestsSupported != nil {
		in, out := &in.PushedAuthorizationRequestsSupported, &out.PushedAuthorizationRequestsSupported
		*out = new(bool)
		**out = **in
	}
	if in.SandboxVersion != nil {
		in, out := &in.SandboxVersion, &out.SandboxVersion
		*out = new(string)
		**out = **in
	}
	if in.SessionCookie != nil {
		in, out := &in.SessionCookie, &out.SessionCookie
		*out = make([]SessionCookieParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SessionLifetime != nil {
		in, out := &in.SessionLifetime, &out.SessionLifetime
		*out = new(float64)
		**out = **in
	}
	if in.Sessions != nil {
		in, out := &in.Sessions, &out.Sessions
		*out = make([]SessionsParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SupportEmail != nil {
		in, out := &in.SupportEmail, &out.SupportEmail
		*out = new(string)
		**out = **in
	}
	if in.SupportURL != nil {
		in, out := &in.SupportURL, &out.SupportURL
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantParameters.
func (in *TenantParameters) DeepCopy() *TenantParameters {
	if in == nil {
		return nil
	}
	out := new(TenantParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantSpec) DeepCopyInto(out *TenantSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantSpec.
func (in *TenantSpec) DeepCopy() *TenantSpec {
	if in == nil {
		return nil
	}
	out := new(TenantSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantStatus) DeepCopyInto(out *TenantStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantStatus.
func (in *TenantStatus) DeepCopy() *TenantStatus {
	if in == nil {
		return nil
	}
	out := new(TenantStatus)
	in.DeepCopyInto(out)
	return out
}
