//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Partials) DeepCopyInto(out *Partials) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Partials.
func (in *Partials) DeepCopy() *Partials {
	if in == nil {
		return nil
	}
	out := new(Partials)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Partials) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PartialsInitParameters) DeepCopyInto(out *PartialsInitParameters) {
	*out = *in
	if in.FormContentEnd != nil {
		in, out := &in.FormContentEnd, &out.FormContentEnd
		*out = new(string)
		**out = **in
	}
	if in.FormContentStart != nil {
		in, out := &in.FormContentStart, &out.FormContentStart
		*out = new(string)
		**out = **in
	}
	if in.FormFooterEnd != nil {
		in, out := &in.FormFooterEnd, &out.FormFooterEnd
		*out = new(string)
		**out = **in
	}
	if in.FormFooterStart != nil {
		in, out := &in.FormFooterStart, &out.FormFooterStart
		*out = new(string)
		**out = **in
	}
	if in.Prompt != nil {
		in, out := &in.Prompt, &out.Prompt
		*out = new(string)
		**out = **in
	}
	if in.SecondaryActionsEnd != nil {
		in, out := &in.SecondaryActionsEnd, &out.SecondaryActionsEnd
		*out = new(string)
		**out = **in
	}
	if in.SecondaryActionsStart != nil {
		in, out := &in.SecondaryActionsStart, &out.SecondaryActionsStart
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PartialsInitParameters.
func (in *PartialsInitParameters) DeepCopy() *PartialsInitParameters {
	if in == nil {
		return nil
	}
	out := new(PartialsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PartialsList) DeepCopyInto(out *PartialsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Partials, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PartialsList.
func (in *PartialsList) DeepCopy() *PartialsList {
	if in == nil {
		return nil
	}
	out := new(PartialsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PartialsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PartialsObservation) DeepCopyInto(out *PartialsObservation) {
	*out = *in
	if in.FormContentEnd != nil {
		in, out := &in.FormContentEnd, &out.FormContentEnd
		*out = new(string)
		**out = **in
	}
	if in.FormContentStart != nil {
		in, out := &in.FormContentStart, &out.FormContentStart
		*out = new(string)
		**out = **in
	}
	if in.FormFooterEnd != nil {
		in, out := &in.FormFooterEnd, &out.FormFooterEnd
		*out = new(string)
		**out = **in
	}
	if in.FormFooterStart != nil {
		in, out := &in.FormFooterStart, &out.FormFooterStart
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Prompt != nil {
		in, out := &in.Prompt, &out.Prompt
		*out = new(string)
		**out = **in
	}
	if in.SecondaryActionsEnd != nil {
		in, out := &in.SecondaryActionsEnd, &out.SecondaryActionsEnd
		*out = new(string)
		**out = **in
	}
	if in.SecondaryActionsStart != nil {
		in, out := &in.SecondaryActionsStart, &out.SecondaryActionsStart
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PartialsObservation.
func (in *PartialsObservation) DeepCopy() *PartialsObservation {
	if in == nil {
		return nil
	}
	out := new(PartialsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PartialsParameters) DeepCopyInto(out *PartialsParameters) {
	*out = *in
	if in.FormContentEnd != nil {
		in, out := &in.FormContentEnd, &out.FormContentEnd
		*out = new(string)
		**out = **in
	}
	if in.FormContentStart != nil {
		in, out := &in.FormContentStart, &out.FormContentStart
		*out = new(string)
		**out = **in
	}
	if in.FormFooterEnd != nil {
		in, out := &in.FormFooterEnd, &out.FormFooterEnd
		*out = new(string)
		**out = **in
	}
	if in.FormFooterStart != nil {
		in, out := &in.FormFooterStart, &out.FormFooterStart
		*out = new(string)
		**out = **in
	}
	if in.Prompt != nil {
		in, out := &in.Prompt, &out.Prompt
		*out = new(string)
		**out = **in
	}
	if in.SecondaryActionsEnd != nil {
		in, out := &in.SecondaryActionsEnd, &out.SecondaryActionsEnd
		*out = new(string)
		**out = **in
	}
	if in.SecondaryActionsStart != nil {
		in, out := &in.SecondaryActionsStart, &out.SecondaryActionsStart
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PartialsParameters.
func (in *PartialsParameters) DeepCopy() *PartialsParameters {
	if in == nil {
		return nil
	}
	out := new(PartialsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PartialsSpec) DeepCopyInto(out *PartialsSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PartialsSpec.
func (in *PartialsSpec) DeepCopy() *PartialsSpec {
	if in == nil {
		return nil
	}
	out := new(PartialsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PartialsStatus) DeepCopyInto(out *PartialsStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PartialsStatus.
func (in *PartialsStatus) DeepCopy() *PartialsStatus {
	if in == nil {
		return nil
	}
	out := new(PartialsStatus)
	in.DeepCopyInto(out)
	return out
}
