// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type PartialsInitParameters struct {

	// (String, Deprecated) Content that goes at the end of the form.
	// Content that goes at the end of the form.
	FormContentEnd *string `json:"formContentEnd,omitempty" tf:"form_content_end,omitempty"`

	// (String, Deprecated) Content that goes at the start of the form.
	// Content that goes at the start of the form.
	FormContentStart *string `json:"formContentStart,omitempty" tf:"form_content_start,omitempty"`

	// (String, Deprecated) Footer content for the end of the footer.
	// Footer content for the end of the footer.
	FormFooterEnd *string `json:"formFooterEnd,omitempty" tf:"form_footer_end,omitempty"`

	// (String, Deprecated) Footer content for the start of the footer.
	// Footer content for the start of the footer.
	FormFooterStart *string `json:"formFooterStart,omitempty" tf:"form_footer_start,omitempty"`

	// id, login, login-password, signup, signup-id, signup-password, login-passwordless, customized-consent.
	// The prompt that you are adding partials for. Options are: `login-id`, `login`, `login-password`, `signup`, `signup-id`, `signup-password`, `login-passwordless`, `customized-consent`.
	Prompt *string `json:"prompt,omitempty" tf:"prompt,omitempty"`

	// (String, Deprecated) Actions that go at the end of secondary actions.
	// Actions that go at the end of secondary actions.
	SecondaryActionsEnd *string `json:"secondaryActionsEnd,omitempty" tf:"secondary_actions_end,omitempty"`

	// (String, Deprecated) Actions that go at the start of secondary actions.
	// Actions that go at the start of secondary actions.
	SecondaryActionsStart *string `json:"secondaryActionsStart,omitempty" tf:"secondary_actions_start,omitempty"`
}

type PartialsObservation struct {

	// (String, Deprecated) Content that goes at the end of the form.
	// Content that goes at the end of the form.
	FormContentEnd *string `json:"formContentEnd,omitempty" tf:"form_content_end,omitempty"`

	// (String, Deprecated) Content that goes at the start of the form.
	// Content that goes at the start of the form.
	FormContentStart *string `json:"formContentStart,omitempty" tf:"form_content_start,omitempty"`

	// (String, Deprecated) Footer content for the end of the footer.
	// Footer content for the end of the footer.
	FormFooterEnd *string `json:"formFooterEnd,omitempty" tf:"form_footer_end,omitempty"`

	// (String, Deprecated) Footer content for the start of the footer.
	// Footer content for the start of the footer.
	FormFooterStart *string `json:"formFooterStart,omitempty" tf:"form_footer_start,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// id, login, login-password, signup, signup-id, signup-password, login-passwordless, customized-consent.
	// The prompt that you are adding partials for. Options are: `login-id`, `login`, `login-password`, `signup`, `signup-id`, `signup-password`, `login-passwordless`, `customized-consent`.
	Prompt *string `json:"prompt,omitempty" tf:"prompt,omitempty"`

	// (String, Deprecated) Actions that go at the end of secondary actions.
	// Actions that go at the end of secondary actions.
	SecondaryActionsEnd *string `json:"secondaryActionsEnd,omitempty" tf:"secondary_actions_end,omitempty"`

	// (String, Deprecated) Actions that go at the start of secondary actions.
	// Actions that go at the start of secondary actions.
	SecondaryActionsStart *string `json:"secondaryActionsStart,omitempty" tf:"secondary_actions_start,omitempty"`
}

type PartialsParameters struct {

	// (String, Deprecated) Content that goes at the end of the form.
	// Content that goes at the end of the form.
	// +kubebuilder:validation:Optional
	FormContentEnd *string `json:"formContentEnd,omitempty" tf:"form_content_end,omitempty"`

	// (String, Deprecated) Content that goes at the start of the form.
	// Content that goes at the start of the form.
	// +kubebuilder:validation:Optional
	FormContentStart *string `json:"formContentStart,omitempty" tf:"form_content_start,omitempty"`

	// (String, Deprecated) Footer content for the end of the footer.
	// Footer content for the end of the footer.
	// +kubebuilder:validation:Optional
	FormFooterEnd *string `json:"formFooterEnd,omitempty" tf:"form_footer_end,omitempty"`

	// (String, Deprecated) Footer content for the start of the footer.
	// Footer content for the start of the footer.
	// +kubebuilder:validation:Optional
	FormFooterStart *string `json:"formFooterStart,omitempty" tf:"form_footer_start,omitempty"`

	// id, login, login-password, signup, signup-id, signup-password, login-passwordless, customized-consent.
	// The prompt that you are adding partials for. Options are: `login-id`, `login`, `login-password`, `signup`, `signup-id`, `signup-password`, `login-passwordless`, `customized-consent`.
	// +kubebuilder:validation:Optional
	Prompt *string `json:"prompt,omitempty" tf:"prompt,omitempty"`

	// (String, Deprecated) Actions that go at the end of secondary actions.
	// Actions that go at the end of secondary actions.
	// +kubebuilder:validation:Optional
	SecondaryActionsEnd *string `json:"secondaryActionsEnd,omitempty" tf:"secondary_actions_end,omitempty"`

	// (String, Deprecated) Actions that go at the start of secondary actions.
	// Actions that go at the start of secondary actions.
	// +kubebuilder:validation:Optional
	SecondaryActionsStart *string `json:"secondaryActionsStart,omitempty" tf:"secondary_actions_start,omitempty"`
}

// PartialsSpec defines the desired state of Partials
type PartialsSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     PartialsParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider PartialsInitParameters `json:"initProvider,omitempty"`
}

// PartialsStatus defines the observed state of Partials.
type PartialsStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        PartialsObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Partials is the Schema for the Partialss API. With this resource, you can manage a customized sign up and login experience by adding custom content, form elements and css/javascript. You can read more about this here https://auth0.com/docs/customize/universal-login-pages/customize-signup-and-login-prompts.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,auth0}
type Partials struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.prompt) || (has(self.initProvider) && has(self.initProvider.prompt))",message="spec.forProvider.prompt is a required parameter"
	Spec   PartialsSpec   `json:"spec"`
	Status PartialsStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// PartialsList contains a list of Partialss
type PartialsList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Partials `json:"items"`
}

// Repository type metadata.
var (
	Partials_Kind             = "Partials"
	Partials_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Partials_Kind}.String()
	Partials_KindAPIVersion   = Partials_Kind + "." + CRDGroupVersion.String()
	Partials_GroupVersionKind = CRDGroupVersion.WithKind(Partials_Kind)
)

func init() {
	SchemeBuilder.Register(&Partials{}, &PartialsList{})
}
