//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Prompt) DeepCopyInto(out *Prompt) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Prompt.
func (in *Prompt) DeepCopy() *Prompt {
	if in == nil {
		return nil
	}
	out := new(Prompt)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Prompt) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PromptInitParameters) DeepCopyInto(out *PromptInitParameters) {
	*out = *in
	if in.IdentifierFirst != nil {
		in, out := &in.IdentifierFirst, &out.IdentifierFirst
		*out = new(bool)
		**out = **in
	}
	if in.UniversalLoginExperience != nil {
		in, out := &in.UniversalLoginExperience, &out.UniversalLoginExperience
		*out = new(string)
		**out = **in
	}
	if in.WebauthnPlatformFirstFactor != nil {
		in, out := &in.WebauthnPlatformFirstFactor, &out.WebauthnPlatformFirstFactor
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PromptInitParameters.
func (in *PromptInitParameters) DeepCopy() *PromptInitParameters {
	if in == nil {
		return nil
	}
	out := new(PromptInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PromptList) DeepCopyInto(out *PromptList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Prompt, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PromptList.
func (in *PromptList) DeepCopy() *PromptList {
	if in == nil {
		return nil
	}
	out := new(PromptList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PromptList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PromptObservation) DeepCopyInto(out *PromptObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.IdentifierFirst != nil {
		in, out := &in.IdentifierFirst, &out.IdentifierFirst
		*out = new(bool)
		**out = **in
	}
	if in.UniversalLoginExperience != nil {
		in, out := &in.UniversalLoginExperience, &out.UniversalLoginExperience
		*out = new(string)
		**out = **in
	}
	if in.WebauthnPlatformFirstFactor != nil {
		in, out := &in.WebauthnPlatformFirstFactor, &out.WebauthnPlatformFirstFactor
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PromptObservation.
func (in *PromptObservation) DeepCopy() *PromptObservation {
	if in == nil {
		return nil
	}
	out := new(PromptObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PromptParameters) DeepCopyInto(out *PromptParameters) {
	*out = *in
	if in.IdentifierFirst != nil {
		in, out := &in.IdentifierFirst, &out.IdentifierFirst
		*out = new(bool)
		**out = **in
	}
	if in.UniversalLoginExperience != nil {
		in, out := &in.UniversalLoginExperience, &out.UniversalLoginExperience
		*out = new(string)
		**out = **in
	}
	if in.WebauthnPlatformFirstFactor != nil {
		in, out := &in.WebauthnPlatformFirstFactor, &out.WebauthnPlatformFirstFactor
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PromptParameters.
func (in *PromptParameters) DeepCopy() *PromptParameters {
	if in == nil {
		return nil
	}
	out := new(PromptParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PromptSpec) DeepCopyInto(out *PromptSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PromptSpec.
func (in *PromptSpec) DeepCopy() *PromptSpec {
	if in == nil {
		return nil
	}
	out := new(PromptSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PromptStatus) DeepCopyInto(out *PromptStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PromptStatus.
func (in *PromptStatus) DeepCopy() *PromptStatus {
	if in == nil {
		return nil
	}
	out := new(PromptStatus)
	in.DeepCopyInto(out)
	return out
}
