apiVersion: tokenexchangeprofile.auth0.com/v1alpha1
kind: ExchangeProfile
metadata:
  annotations:
    meta.upbound.io/example-id: tokenexchangeprofile/v1alpha1/exchangeprofile
  labels:
    testing.upbound.io/example-name: my_token_exchange_profile
  name: my-token-exchange-profile
spec:
  forProvider:
    actionId: ${auth0_action.my_action.id}
    name: token-exchange-prof
    subjectTokenType: https://acme.com/cis-token
    type: custom_authentication

---

apiVersion: action.auth0.com/v1alpha1
kind: Action
metadata:
  annotations:
    meta.upbound.io/example-id: tokenexchangeprofile/v1alpha1/exchangeprofile
  labels:
    testing.upbound.io/example-name: my_action
  name: my-action
spec:
  forProvider:
    code: "exports.onContinuePostLogin = async (event, api) => {\n\tconsole.log(\"foo\")\n};\"\n"
    deploy: true
    name: TokenExchange-Action
    supportedTriggers:
    - id: custom-token-exchange
      version: v1
